### ISSUE TITLE
checkptr issue found

### ISSUE THREAD

**Issue by campoy** [dgraph-io/badger#1096]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version devel +7d891d5e4d Tue Oct 22 21:23:03 2019 +0000 linux/amd64
</pre>

### What version of Badger are you using?

Tip (be6402f83d3126230c7fc51543abe7c691e94ed6)

### Does this issue reproduce with the latest master?

Yes

### What are the hardware specifications of the machine (RAM, OS, Disk)?

Linux, N/A

### What did you do?

I ran the tests with `checkptr` enabled.
New in go tip is a checkptr flag: https://groups.google.com/forum/#!msg/golang-dev/SzwDoqoRVJA/IvtnBW5oDwAJ

### What did you expect to see?

All tests should pass

### What did you see instead?

Two unsafe pointer conversions were found. See logs below.

```bash
gotip test -gcflags=all=-d=checkptr ./...
badger 2019/10/22 15:00:36 INFO: All 0 tables opened in 0s
badger 2019/10/22 15:00:36 INFO: DB.Backup Created batch of size: 50 B in 34.925µs.
badger 2019/10/22 15:00:36 INFO: DB.Backup Sent 2 keys
badger 2019/10/22 15:00:36 DEBUG: Storing value log head: {Fid:0 Len:29 Offset:101}
panic: runtime error: unsafe pointer conversion

goroutine 68 [running]:
github.com/dgraph-io/badger/table.(*header).Decode(...)
	/home/francesc/src/github.com/dgraph-io/badger/table/builder.go:57
github.com/dgraph-io/badger/table.(*blockIterator).setIdx(0xc0009a2010, 0x2)
	/home/francesc/src/github.com/dgraph-io/badger/table/iterator.go:82 +0x20a
github.com/dgraph-io/badger/table.(*blockIterator).seekToLast(...)
	/home/francesc/src/github.com/dgraph-io/badger/table/iterator.go:141
github.com/dgraph-io/badger/table.(*Iterator).seekToLast(0xc0009a2000)
	/home/francesc/src/github.com/dgraph-io/badger/table/iterator.go:217 +0x18d
github.com/dgraph-io/badger/table.(*Iterator).Rewind(0xc0009a2000)
	/home/francesc/src/github.com/dgraph-io/badger/table/iterator.go:378 +0x34
github.com/dgraph-io/badger/table.(*Table).initBiggestAndSmallest(0xc000998000, 0x0, 0x0)
	/home/francesc/src/github.com/dgraph-io/badger/table/table.go:269 +0xf9
github.com/dgraph-io/badger/table.OpenInMemoryTable(0xc000858000, 0xfb, 0x100000, 0x1, 0xc000856000, 0x0, 0x0, 0x2)
	/home/francesc/src/github.com/dgraph-io/badger/table/table.go:254 +0xac
github.com/dgraph-io/badger.(*DB).handleFlushTask(0xc00034e000, 0xc0000b0380, 0x1d00000000, 0x65, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/francesc/src/github.com/dgraph-io/badger/db.go:942 +0x618
github.com/dgraph-io/badger.(*DB).flushMemtable(0xc00034e000, 0xc0000b07a0, 0x0, 0x0)
	/home/francesc/src/github.com/dgraph-io/badger/db.go:989 +0x16b
github.com/dgraph-io/badger.Open.func4(0xc0000be320)
	/home/francesc/src/github.com/dgraph-io/badger/db.go:337 +0x37
created by github.com/dgraph-io/badger.Open
	/home/francesc/src/github.com/dgraph-io/badger/db.go:336 +0x18df
FAIL	github.com/dgraph-io/badger	0.037s
?   	github.com/dgraph-io/badger/badger	[no test files]
?   	github.com/dgraph-io/badger/badger/cmd	[no test files]
?   	github.com/dgraph-io/badger/integration/testgc	[no test files]
?   	github.com/dgraph-io/badger/options	[no test files]
?   	github.com/dgraph-io/badger/pb	[no test files]
ok  	github.com/dgraph-io/badger/skl	0.201s
panic: runtime error: unsafe pointer conversion [recovered]
	panic: runtime error: unsafe pointer conversion

goroutine 22 [running]:
testing.tRunner.func1(0xc000104400)
	/home/francesc/src/github.com/golang/go/src/testing/testing.go:881 +0x3a3
panic(0x949fa0, 0xc0000aa0e0)
	/home/francesc/src/github.com/golang/go/src/runtime/panic.go:679 +0x1b2
github.com/dgraph-io/badger/table.(*header).Decode(...)
	/home/francesc/src/github.com/dgraph-io/badger/table/builder.go:57
github.com/dgraph-io/badger/table.(*blockIterator).setIdx(0xc00018e0d0, 0xa5)
	/home/francesc/src/github.com/dgraph-io/badger/table/iterator.go:82 +0x20a
github.com/dgraph-io/badger/table.(*blockIterator).seekToLast(...)
	/home/francesc/src/github.com/dgraph-io/badger/table/iterator.go:141
github.com/dgraph-io/badger/table.(*Iterator).seekToLast(0xc00018e0c0)
	/home/francesc/src/github.com/dgraph-io/badger/table/iterator.go:217 +0x18d
github.com/dgraph-io/badger/table.(*Iterator).Rewind(0xc00018e0c0)
	/home/francesc/src/github.com/dgraph-io/badger/table/iterator.go:378 +0x34
github.com/dgraph-io/badger/table.(*Table).initBiggestAndSmallest(0xc00018e000, 0x0, 0x0)
	/home/francesc/src/github.com/dgraph-io/badger/table/table.go:269 +0xf9
github.com/dgraph-io/badger/table.OpenTable(0xc0000b88c0, 0x0, 0x0, 0x3f847ae147ae147b, 0x1000, 0x0, 0x0, 0x0, 0x20, 0x0, ...)
	/home/francesc/src/github.com/dgraph-io/badger/table/table.go:228 +0x336
github.com/dgraph-io/badger/table.TestTableIndex.func2(0xc000104400)
	/home/francesc/src/github.com/dgraph-io/badger/table/builder_test.go:82 +0x84b
testing.tRunner(0xc000104400, 0x9a7dc8)
	/home/francesc/src/github.com/golang/go/src/testing/testing.go:916 +0xc9
created by testing.(*T).Run
	/home/francesc/src/github.com/golang/go/src/testing/testing.go:967 +0x351
FAIL	github.com/dgraph-io/badger/table	0.058s
ok  	github.com/dgraph-io/badger/trie	
```

**Comment by jarifibrahim** [comment]
The following test also fails
```
--- FAIL: TestTruncateVlogWithClose (0.06s)
panic: runtime error: unsafe pointer conversion [recovered]
	panic: runtime error: unsafe pointer conversion

goroutine 53572 [running]:
testing.tRunner.func1(0xc0003a3e00)
	/home/francesc/src/github.com/golang/go/src/testing/testing.go:881 +0x3a3
panic(0xa43860, 0xc088c4b760)
	/home/francesc/src/github.com/golang/go/src/runtime/panic.go:679 +0x1b2
github.com/dgraph-io/badger.(*valuePointer).Decode(...)
	/home/francesc/src/github.com/dgraph-io/badger/structs.go:42
github.com/dgraph-io/badger.Open(0xc087f24f80, 0x19, 0xc087f24f80, 0x19, 0x1, 0x2, 0x2, 0x1, 0x100, 0xb5e4c0, ...)
	/home/francesc/src/github.com/dgraph-io/badger/db.go:350 +0x16c5
github.com/dgraph-io/badger.TestTruncateVlogWithClose(0xc0003a3e00)
	/home/francesc/src/github.com/dgraph-io/badger/db2_test.go:72 +0x416
testing.tRunner(0xc0003a3e00, 0xab3c18)
	/home/francesc/src/github.com/golang/go/src/testing/testing.go:916 +0xc9
created by testing.(*T).Run
```

In both the failures, we're copying over data from slice into a struct and we might run into issues if they are not aligned properly.
