### ISSUE TITLE
TestDropAllWithPendingTxn is flaky and fails with seg fault

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#1131]
`TestDropAllWithPendingTxn` fails on TeamCity intermittently. It seems like we have a bug in vlog locking and unlocking. The `buf` used by `header.Decode` becomes invalid while it is in use.

```
------- Stdout: -------
=== RUN   TestDropAllWithPendingTxn
badger 2019/11/23 09:16:22 INFO: All 0 tables opened in 0s
badger 2019/11/23 09:16:23 DEBUG: Flushing memtable, mt.size=34871 size of flushChan: 0
badger 2019/11/23 09:16:23 DEBUG: Storing value log head: {Fid:0 Len:30 Offset:4831937}
badger 2019/11/23 09:16:23 DEBUG: Storing value log head: {Fid:1 Len:30 Offset:4026620}
badger 2019/11/23 09:16:23 DEBUG: Flushing memtable, mt.size=34953 size of flushChan: 0
badger 2019/11/23 09:16:23 DEBUG: Flushing memtable, mt.size=28997 size of flushChan: 0
badger 2019/11/23 09:16:23 DEBUG: Storing value log head: {Fid:2 Len:30 Offset:2415968}
badger 2019/11/23 09:16:24 DEBUG: Storing value log head: {Fid:3 Len:30 Offset:1610642}
badger 2019/11/23 09:16:24 DEBUG: Flushing memtable, mt.size=34817 size of flushChan: 0
badger 2019/11/23 09:16:24 DEBUG: Storing value log head: {Fid:4 Len:30 Offset:805316}
badger 2019/11/23 09:16:24 DEBUG: Flushing memtable, mt.size=34977 size of flushChan: 0
badger 2019/11/23 09:16:24 INFO: Got compaction priority: {level:0 score:1 dropPrefix:[]}
badger 2019/11/23 09:16:24 INFO: Running for level: 0
badger 2019/11/23 09:16:24 DEBUG: LOG Compact. Added 2847 keys. Skipped 0 keys. Iteration took: 41.835932ms
badger 2019/11/23 09:16:24 DEBUG: Discard stats: map[]
badger 2019/11/23 09:16:24 INFO: LOG Compact 0->1, del 5 tables, add 1 tables, took 56.899814ms
badger 2019/11/23 09:16:24 INFO: Compaction for level: 0 DONE
badger 2019/11/23 09:16:24 DEBUG: Flushing memtable, mt.size=34843 size of flushChan: 0
badger 2019/11/23 09:16:24 DEBUG: Storing value log head: {Fid:4 Len:30 Offset:5637272}
badger 2019/11/23 09:16:25 DEBUG: Flushing memtable, mt.size=34831 size of flushChan: 0
badger 2019/11/23 09:16:25 DEBUG: Storing value log head: {Fid:5 Len:30 Offset:4831946}
badger 2019/11/23 09:16:25 DEBUG: Flushing memtable, mt.size=34699 size of flushChan: 0
badger 2019/11/23 09:16:25 DEBUG: Storing value log head: {Fid:6 Len:30 Offset:4026620}
badger 2019/11/23 09:16:25 DEBUG: Storing value log head: {Fid:7 Len:31 Offset:3221300}
badger 2019/11/23 09:16:25 DEBUG: Flushing memtable, mt.size=34765 size of flushChan: 0
badger 2019/11/23 09:16:26 DEBUG: Storing value log head: {Fid:8 Len:31 Offset:2415973}
badger 2019/11/23 09:16:26 DEBUG: Flushing memtable, mt.size=34793 size of flushChan: 0
badger 2019/11/23 09:16:26 INFO: Got compaction priority: {level:0 score:1 dropPrefix:[]}
badger 2019/11/23 09:16:26 INFO: Running for level: 0
badger 2019/11/23 09:16:26 DEBUG: Storing value log head: {Fid:9 Len:31 Offset:1610645}
badger 2019/11/23 09:16:26 DEBUG: Flushing memtable, mt.size=34785 size of flushChan: 0
badger 2019/11/23 09:16:26 DEBUG: LOG Compact. Added 3601 keys. Skipped 0 keys. Iteration took: 51.973624ms
badger 2019/11/23 09:16:26 DEBUG: LOG Compact. Added 2191 keys. Skipped 0 keys. Iteration took: 33.859626ms
badger 2019/11/23 09:16:26 DEBUG: Discard stats: map[]
badger 2019/11/23 09:16:26 INFO: LOG Compact 0->1, del 6 tables, add 2 tables, took 99.521277ms
badger 2019/11/23 09:16:26 INFO: Compaction for level: 0 DONE
badger 2019/11/23 09:16:26 DEBUG: Storing value log head: {Fid:10 Len:31 Offset:805317}
badger 2019/11/23 09:16:26 DEBUG: Flushing memtable, mt.size=34869 size of flushChan: 0
badger 2019/11/23 09:16:26 DEBUG: Flushing memtable, mt.size=34835 size of flushChan: 0
badger 2019/11/23 09:16:26 DEBUG: Storing value log head: {Fid:10 Len:31 Offset:5637285}
badger 2019/11/23 09:16:27 DEBUG: Flushing memtable, mt.size=34847 size of flushChan: 0
badger 2019/11/23 09:16:27 DEBUG: Storing value log head: {Fid:11 Len:31 Offset:4831957}
badger 2019/11/23 09:16:27 DEBUG: Flushing memtable, mt.size=34795 size of flushChan: 0
badger 2019/11/23 09:16:27 DEBUG: Storing value log head: {Fid:12 Len:31 Offset:4026629}
badger 2019/11/23 09:16:27 INFO: Got compaction priority: {level:0 score:1 dropPrefix:[]}
badger 2019/11/23 09:16:27 INFO: Running for level: 0
badger 2019/11/23 09:16:27 DEBUG: LOG Compact. Added 3605 keys. Skipped 0 keys. Iteration took: 56.53958ms
badger 2019/11/23 09:16:27 DEBUG: Storing value log head: {Fid:13 Len:31 Offset:3221301}
badger 2019/11/23 09:16:27 DEBUG: Flushing memtable, mt.size=34957 size of flushChan: 0
badger 2019/11/23 09:16:27 DEBUG: LOG Compact. Added 3603 keys. Skipped 0 keys. Iteration took: 61.602337ms
badger 2019/11/23 09:16:27 DEBUG: LOG Compact. Added 1529 keys. Skipped 0 keys. Iteration took: 26.732709ms
badger 2019/11/23 09:16:27 DEBUG: Discard stats: map[]
badger 2019/11/23 09:16:27 INFO: LOG Compact 0->1, del 7 tables, add 3 tables, took 158.748677ms
badger 2019/11/23 09:16:27 INFO: Compaction for level: 0 DONE
badger 2019/11/23 09:16:28 DEBUG: Storing value log head: {Fid:14 Len:31 Offset:2415973}
badger 2019/11/23 09:16:28 DEBUG: Flushing memtable, mt.size=34885 size of flushChan: 0
badger 2019/11/23 09:16:31 INFO: DropAll called. Blocking writes...
badger 2019/11/23 09:16:31 INFO: Writes flushed. Stopping compactions now...
badger 2019/11/23 09:16:31 INFO: Deleted 5 SSTables. Now deleting value logs...
badger 2019/11/23 09:16:31 INFO: Value logs deleted. Creating value log file: 0
unexpected fault address badger 2019/11/23 09:16:31 INFO: Deleted 15 value log files. DropAll done.
0x7ff4c2cdc206
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7ff4c2cdc206 pc=0xa95575]

goroutine 1720022 [running]:
runtime.throw(0xd1f5e2, 0x5)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc068dc9b38 sp=0xc068dc9b08 pc=0x4478a2
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:387 +0x47e fp=0xc068dc9b68 sp=0xc068dc9b38 pc=0x45dc7e
github.com/dgraph-io/badger.(*header).Decode(0xc068dc9c80, 0x7ff4c2cdc205, 0x2019, 0x4d3dfb, 0x7ff4c2cdc205)
	/home/pawan0201/go/src/github.com/dgraph-io/badger/structs.go:97 +0x55 fp=0xc068dc9bd0 sp=0xc068dc9b68 pc=0xa95575
github.com/dgraph-io/badger.(*valueLog).Read(0xc00192a1c8, 0x201900000000, 0x52c205, 0xc05cb43d40, 0xc, 0x10, 0x1, 0xc, 0x0, 0x0)
	/home/pawan0201/go/src/github.com/dgraph-io/badger/value.go:1433 +0x1a5 fp=0xc068dc9d40 sp=0xc068dc9bd0 pc=0xaaae75
github.com/dgraph-io/badger.(*Item).yieldItemValue(0xc05ca55810, 0xa543a6, 0xc03b5d8cc0, 0x0, 0x0, 0x0, 0x0)
	/home/pawan0201/go/src/github.com/dgraph-io/badger/iterator.go:170 +0x25b fp=0xc068dc9f10 sp=0xc068dc9d40 pc=0xa6984b
github.com/dgraph-io/badger.(*Item).prefetchValue(0xc05ca55810)
	/home/pawan0201/go/src/github.com/dgraph-io/badger/iterator.go:217 +0x51 fp=0xc068dc9fb8 sp=0xc068dc9f10 pc=0xa6a311
github.com/dgraph-io/badger.(*Iterator).fill.func1(0xc05ca55810)
	/home/pawan0201/go/src/github.com/dgraph-io/badger/iterator.go:681 +0x39 fp=0xc068dc9fd8 sp=0xc068dc9fb8 pc=0xaee719
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc068dc9fe0 sp=0xc068dc9fd8 pc=0x4778b1
created by github.com/dgraph-io/badger.(*Iterator).fill
	/home/pawan0201/go/src/github.com/dgraph-io/badger/iterator.go:679 +0x434

```
The complete log can be found here https://gist.github.com/jarifibrahim/0b5c7830a5c4450aa9280a9101f44d34
Example of a failed build https://teamcity.dgraph.io/viewLog.html?buildId=32704&buildTypeId=Badger_UnitTests

**Comment by jarifibrahim** [comment]
The first failure was seen on PR https://github.com/dgraph-io/badger/pull/1052.

**Comment by jarifibrahim** [comment]
This issue has been fixed via https://github.com/dgraph-io/badger/pull/1150
