### ISSUE TITLE
Seg fault in header.Decode

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#1136]
Related to https://github.com/dgraph-io/badger/issues/1131 and https://github.com/dgraph-io/dgraph/issues/4288

The `header.Decode()` call is failing with a segfault. This might happen if we `un-mmap` a buffer which was being used.

```
I1120 22:38:19.739601   17317 log.go:34] Rolling up Created batch of size: 4.4 MB in 3.375185ms.
I1120 22:38:19.830047   17317 log.go:34] Rolling up Created batch of size: 4.2 MB in 44.563542ms.
I1120 22:38:19.964863   17317 log.go:34] Rolling up Created batch of size: 4.2 MB in 7.138776ms.
I1120 22:38:19.998105   17317 log.go:34] Rolling up Created batch of size: 4.2 MB in 6.573937ms.
I1120 22:38:20.103270   17317 log.go:34] Rolling up Created batch of size: 2.6 MB in 50.209836ms.
I1120 22:38:20.169139   17317 log.go:34] Rolling up Created batch of size: 4.2 MB in 5.352161ms.
unexpected fault address 0x7fc6ff030e7f
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fc6ff030e7f pc=0x11612d5]

goroutine 3132541 [running]:
runtime.throw(0x17277a8, 0x5)
	/usr/lib/golang/src/runtime/panic.go:617 +0x72 fp=0xc01a7428c8 sp=0xc01a742898 pc=0x937f52
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:397 +0x401 fp=0xc01a7428f8 sp=0xc01a7428c8 pc=0x94e0d1
github.com/dgraph-io/badger.(*header).Decode(0xc01a7429a0, 0x7fc6ff030e7f, 0x957, 0x40fcf17f, 0x7fc6ff030e7f)
	/home/miguel/go/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/structs.go:82 +0x35 fp=0xc01a742940 sp=0xc01a7428f8 pc=0x11612d5
github.com/dgraph-io/badger.(*valueLog).Read(0xc000057a08, 0x95700000018, 0x3f030e7f, 0xc0191e41a0, 0x0, 0xc02c688000, 0xc01a742a78, 0x1013be3, 0xc02c6860a0, 0x1)
	/home/miguel/go/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/value.go:1166 +0xf1 fp=0xc01a742a00 sp=0xc01a742940 pc=0x116d451
github.com/dgraph-io/badger.(*Item).yieldItemValue(0xc0122ee370, 0x35, 0x48, 0x60, 0xc017952720, 0x0, 0xc02c6880c0)
	/home/miguel/go/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/iterator.go:170 +0x11e fp=0xc01a742b60 sp=0xc01a742a00 pc=0x114875e
github.com/dgraph-io/badger.(*Item).Value(0xc0122ee370, 0xc01a742bf0, 0x0, 0x0)
	/home/miguel/go/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/iterator.go:105 +0xe8 fp=0xc01a742bd0 sp=0xc01a742b60 pc=0x11481d8
github.com/dgraph-io/dgraph/posting.unmarshalOrCopy(0xc017952720, 0xc0122ee370, 0x0, 0xc02c68a030)
	/home/miguel/go/src/github.com/dgraph-io/dgraph/posting/mvcc.go:131 +0x53 fp=0xc01a742c10 sp=0xc01a742bd0 pc=0x1317dd3
github.com/dgraph-io/dgraph/posting.ReadPostingList(0xc02c68a030, 0x2d, 0x2d, 0xc017ec01e0, 0x0, 0x64, 0x100)
	/home/miguel/go/src/github.com/dgraph-io/dgraph/posting/mvcc.go:166 +0x4c9 fp=0xc01a742cb8 sp=0xc01a742c10 pc=0x13182c9
github.com/dgraph-io/dgraph/posting.getNew(0xc02c68a030, 0x2d, 0x2d, 0xc000057880, 0x0, 0x0, 0x0)
	/home/miguel/go/src/github.com/dgraph-io/dgraph/posting/mvcc.go:217 +0x1e1 fp=0xc01a742d70 sp=0xc01a742cb8 pc=0x1318571
github.com/dgraph-io/dgraph/posting.(*LocalCache).getInternal(0x0, 0xc02c68a030, 0x2d, 0x2d, 0xc02c68a001, 0x2d, 0x2d, 0xc01470fea0)
	/home/miguel/go/src/github.com/dgraph-io/dgraph/posting/lists.go:233 +0x330 fp=0xc01a742de0 sp=0xc01a742d70 pc=0x1316f70
github.com/dgraph-io/dgraph/posting.(*LocalCache).Get(...)
	/home/miguel/go/src/github.com/dgraph-io/dgraph/posting/lists.go:267
github.com/dgraph-io/dgraph/worker.(*queryState).handleUidPostings.func1(0x0, 0x1, 0xc0167fc4e0, 0x940d46)
	/home/miguel/go/src/github.com/dgraph-io/dgraph/worker/task.go:635 +0x238 fp=0xc01a742f80 sp=0xc01a742de0 pc=0x13e0588
github.com/dgraph-io/dgraph/worker.(*queryState).handleUidPostings.func2(0xc0179525a0, 0xc017ec0140, 0x0, 0x1)
	/home/miguel/go/src/github.com/dgraph-io/dgraph/worker/task.go:751 +0x3a fp=0xc01a742fc0 sp=0xc01a742f80 pc=0x13e19aa
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc01a742fc8 sp=0xc01a742fc0 pc=0x968051
created by github.com/dgraph-io/dgraph/worker.(*queryState).handleUidPostings
	/home/miguel/go/src/github.com/dgraph-io/dgraph/worker/task.go:750 +0x3b3
```
Copied over from https://github.com/dgraph-io/dgraph/issues/4288#issuecomment-558141993

**Comment by manishrjain** [comment]
Hey Ibrahim, nice diagnosis. Please make this your top priority to fix.
