### ISSUE TITLE
rarely, nil pointer panic in doCompact go-routine when a badger open.

### ISSUE THREAD

**Issue by peter-kyu** [dgraph-io/badger#1209]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.5 linux/amd64
</pre>

### What version of Badger are you using?
v1.5.4

### Does this issue reproduce with the latest master?
i think it will happen too.

### What are the hardware specifications of the machine (RAM, OS, Disk)?
128g/CentOS Linux release 7.6.1810 (Core)/ssd

### What did you do?
just open a badger db as fileio mode.
i used that option.
```
		doNotCompactOpt:            false,
		levelOneSizeOpt:            400,
		levelSizeMultiplierOpt:     10,
		maxLevelsOpt:               7,
		maxTableSizeOpt:            32,
		numCompactorsOpt:           3,
		numLevelZeroTablesOpt:      5,
		numLevelZeroTablesStallOpt: 10,
		numMemtablesOpt:            1,
		valueLogFileSizeOpt:        128,
		valueThresholdOpt:          100,
		syncWritesOpt:              true,
		tableLoadingModeOpt:        int(options.FileIO), 
		valueLogLoadingModeOpt:     int(options.FileIO), 
		truncateOpt:                true,             

```
and that time vlog and sst files size were almost 100g.

### What did you expect to see?
open it successfully

### What did you see instead?
really rarely get panic in case of go routine scheduling by golang.
this is the panic log i've got.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x94914e]
goroutine 2087487 [running]:
go/src/indexer/vendor/github.com/dgraph-io/badger.(*valueLog).updateGCStats(0xc0033359c8, 0xc028ef8060)
        /home/go/src/indexer/vendor/github.com/dgraph-io/badger/value.go:1233 +0x3e
go/src/indexer/vendor/github.com/dgraph-io/badger.(*levelsController).compactBuildTables(0xc00016a070, 0x1, 0xe7bba0, 0xc0002024e0, 0xc03edec060, 0xc03edec0c0, 
0xc0002823a8, 0x1, 0x1, 0xc012ae63a0, ...)
        /home/go/src/indexer/vendor/github.com/dgraph-io/badger/levels.go:501 +0x1460
go/src/indexer/vendor/github.com/dgraph-io/badger.(*levelsController).runCompactDef(0xc00016a070, 0x1, 0xe7bba0, 0xc0002024e0, 0xc03edec060, 0xc03edec0c0, 0xc00
02823a8, 0x1, 0x1, 0xc012ae63a0, ...)
        /home/go/src/indexer/vendor/github.com/dgraph-io/badger/levels.go:638 +0xd3
go/src/indexer/vendor/github.com/dgraph-io/badger.(*levelsController).doCompact(0xc00016a070, 0x1, 0x3ff0a4ce57ae147b, 0x0, 0x0, 0x0)
        /home/go/src/indexer/vendor/github.com/dgraph-io/badger/levels.go:705 +0x498
go/src/indexer/vendor/github.com/dgraph-io/badger.(*levelsController).runWorker(0xc00016a070, 0xc012ae60c0)
        /home/go/src/indexer/vendor/github.com/dgraph-io/badger/levels.go:254 +0x1c9
created by go/src/indexer/vendor/github.com/dgraph-io/badger.(*levelsController).startCompact
        /home/go/src/indexer/vendor/github.com/dgraph-io/badger/levels.go:233 +0x82
```
it can access a uninitialized (nil point) updateGCStats struct due to go routine scheduling.
https://github.com/dgraph-io/badger/blob/eee160218ee7fe51a25aca6ed4890fb5682bdaca/db.go#L334-L362
that struct can be access in goroutine of  https://github.com/dgraph-io/badger/blob/master/db.go#L336
but initialize in https://github.com/dgraph-io/badger/blob/master/db.go#L359
there is a really rare possibility to run  doCompact goroutine earlier than db.vlog.open.

**Comment by jarifibrahim** [comment]
@peter-kyu I think you're correct. You're using v1.5.4 which is missing a lot of bug fixes and features. Is there are a reason for using the old version?

**Comment by hbbio** [comment]
I'm seeing a maybe related bug using v1.6.0:

```
unexpected fault address 0x4891a144c
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4891a144c pc=0x13def12]

goroutine 70 [running]:
runtime.throw(0x1619da9, 0x5)
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/panic.go:774 +0x72 fp=0xc010f39750 sp=0xc010f39720 pc=0x102f7f2
runtime.sigpanic()
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/signal_unix.go:401 +0x3de fp=0xc010f39780 sp=0xc010f39750 pc=0x1043eae
encoding/binary.bigEndian.Uint32(...)
	/usr/local/Cellar/go/1.13.6/libexec/src/encoding/binary/binary.go:112
github.com/dgraph-io/badger.(*header).Decode(0xc010f39800, 0x4891a144c, 0x21bf, 0x43f40bb2)
	/Users/henri/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/structs.go:73 +0x22 fp=0xc010f397a0 sp=0xc010f39780 pc=0x13def12
github.com/dgraph-io/badger.(*valueLog).Read(0xc000150f68, 0x21bf00000010, 0x3c0bf44c, 0xc00cd8e260, 0x20, 0x0, 0x1, 0x0, 0x100000000000000, 0xc010f39820)
	/Users/henri/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/value.go:1093 +0xf0 fp=0xc010f39860 sp=0xc010f397a0 pc=0x13ea530
github.com/dgraph-io/badger.(*Item).yieldItemValue(0xc018cce2c0, 0xc, 0x52c97cb, 0x13850, 0x0, 0x0, 0x80caee715baef854)
	/Users/henri/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/iterator.go:168 +0x11c fp=0xc010f399b8 sp=0xc010f39860 pc=0x13c749c
github.com/dgraph-io/badger.(*Item).Value(0xc018cce2c0, 0xc010f39b50, 0x0, 0x0)
	/Users/henri/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/iterator.go:103 +0x10e fp=0xc010f39a60 sp=0xc010f399b8 pc=0x13c6ebe
```

This also happens rarely, while doing millions of read/write operations. In my case, my caller code is when accessing the value in a transaction:

```go
item, err := txn.Get(key)
if err != nil {
  return err
}
v := item.Value(fn)
...
```

**Comment by hbbio** [comment]
Update: The bug I encounter rather relates more to #1136 apparently.

I tried again with `v2@master` and haven't reproduced it yet, but it is crashing with another bug:
```log
2020/02/09 12:58:28 Assert failed
github.com/dgraph-io/badger/v2/y.AssertTrue
	/Users/henri/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200205100049-c51748efdced/y/error.go:55
github.com/dgraph-io/badger/v2.(*DB).updateHead
	/Users/henri/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200205100049-c51748efdced/db.go:627
github.com/dgraph-io/badger/v2.(*DB).writeRequests
	/Users/henri/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200205100049-c51748efdced/db.go:721
github.com/dgraph-io/badger/v2.(*DB).doWrites.func1
	/Users/henri/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200205100049-c51748efdced/db.go:759
runtime.goexit
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/asm_amd64.s:1357
```

**Comment by peter-kyu** [comment]
@jarifibrahim
hi~. it was latest version when i released my application. 
i will upgrade with migration code from 1.x to 2.x  soon.
but i think that bug still is in latest version, isn't it?

**Comment by jarifibrahim** [comment]
@peter-kyu I've raised https://github.com/dgraph-io/badger/pull/1226 to fix this in master.

**Comment by jarifibrahim** [comment]
@hbbio your error doesn't seem related to this issue. Can you please create a new issue with all the related information? The error in your case is a serious one. We use head keys to keep track of where to replay the value log file and the pointer should always keep increasing. In the error you've posted it seems like you got a smaller pointer after inserting a bigger one (which should not happen).

Please create a new issue with all the steps you've followed and I'll take a look at it. Thanks! :)
