### ISSUE TITLE
v2: opts.ZSTDCompressionLevel  stalls writes under load.

### ISSUE THREAD

**Issue by gladkikhartem** [dgraph-io/badger#1218]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13beta1 linux/amd64
</pre>

### What version of Badger are you using?
v2.0.1

### Does this issue reproduce with the latest master?
No

### What are the hardware specifications of the machine (RAM, OS, Disk)?
Ryzen 5 2600x
16GB 3200Mhz RAM
Linux Mint 19
Samsung NVMe

### What did you do?
Just load badger with lots of bulk requests
go run main.go 15  // default compression level. 
// If I'll run with go run main.go 0  - performances is stable and works as expected

```
package main

import (
	"fmt"
	"log"
	"math/rand"
	"os"
	"strconv"
	"time"

	"github.com/dgraph-io/badger/v2"
)

func main() {
	lvl, err := strconv.Atoi(os.Args[1])
	if err != nil {
		log.Fatal(err)	
	}
	
	os.RemoveAll("./db")
	opts := badger.DefaultOptions("./db")
	opts.SyncWrites = true
	opts.ZSTDCompressionLevel = lvl
	db, err := badger.Open(opts)
	if err != nil {
		log.Fatal(err)
	}

	batch := 10000
	num := 10000
	start := time.Now()
	for i := 0; i < num; i++ {
		if i % 100 == 0 {
			fmt.Printf("took %.2f sec \n",time.Since(start).Seconds())
			start = time.Now()
		}
		err := db.Update(func(tnx *badger.Txn) error {
			for i := 0; i < batch; i++ {
				err := tnx.Set([]byte(strconv.Itoa(rand.Intn(1000000000))), []byte(strconv.Itoa(rand.Intn(1000000000))))
				if err != nil {
					return err
				}
			}
			return nil
		})
		if err != nil {
			log.Fatal(err)
		}
	}
}
```

### What did you expect to see?
Stable performance over time
```
took 3.13 sec  319099 writes/sec
took 3.18 sec  314381 writes/sec
.... and so on...
.... 
```

### What did you see instead?
```
took 3.11 sec  319124 writes/sec
...
took 3.44 sec  290857 writes/sec
took 65.78 sec  15203 writes/sec  // here no writes happening at all
took 3.22 sec  310690 writes/sec
...

```

The issue does not reproduce if I'll set compression level to 0 (disabled)

System monitor shows CPU load is 8% during that process (on 16 thread CPU) and no Disk reads or Writes are happening.

Stopping Go program during stall gives this:
```
....
...
goroutine 13 [runnable]:
github.com/DataDog/zstd._Cfunc_ZSTD_getDecompressedSize(0x7fcd4b30a2ae, 0x67d, 0xff3)
	_cgo_gotypes.go:309 +0x4e
github.com/DataDog/zstd.Decompress.func2(0xc0000ecbc0, 0x0)
	/home/artem/go/pkg/mod/github.com/!data!dog/zstd@v1.4.1/zstd.go:123 +0xdb
github.com/DataDog/zstd.Decompress(0x0, 0x0, 0x0, 0x7fcd4b30a2ae, 0x67d, 0x19b9bb4, 0x0, 0x0, 0x0, 0x0, ...)
	/home/artem/go/pkg/mod/github.com/!data!dog/zstd@v1.4.1/zstd.go:123 +0x3df
github.com/dgraph-io/badger/v2/y.ZSTDDecompress(...)
	/home/artem/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1/y/zstd_cgo.go:30
github.com/dgraph-io/badger/v2/table.(*Table).decompressData(0xc051fd2240, 0x7fcd4b30a2ae, 0x67d, 0x19b9bb4, 0x67d, 0x19b9bb4, 0x0, 0x0, 0x20301100000000)
	/home/artem/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1/table/table.go:551 +0x12a
github.com/dgraph-io/badger/v2/table.(*Table).block(0xc051fd2240, 0x7e3a, 0x1c, 0x20, 0x11)
	/home/artem/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1/table/table.go:391 +0x1d1
github.com/dgraph-io/badger/v2/table.(*Iterator).next(0xc051fd2000)
	/home/artem/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1/table/iterator.go:296 +0xba
github.com/dgraph-io/badger/v2/table.(*Iterator).next(0xc051fd2000)
	/home/artem/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1/table/iterator.go:311 +0x281
github.com/dgraph-io/badger/v2/table.(*Iterator).Next(0xc051fd2000)
	/home/artem/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1/table/iterator.go:367 +0x47
```

Debug logs from console:
```
badger 2020/02/08 13:26:08 DEBUG: Flushing memtable, mt.size=67596898 size of flushChan: 3
took 2.86 sec  349048 writes/sec
badger 2020/02/08 13:26:11 DEBUG: Flushing memtable, mt.size=67596952 size of flushChan: 4
took 2.84 sec  352169 writes/sec
badger 2020/02/08 13:26:14 DEBUG: Flushing memtable, mt.size=67603593 size of flushChan: 5
took 2.87 sec  349032 writes/sec
badger 2020/02/08 13:26:20 DEBUG: LOG Compact. Added 5202157 keys. Skipped 62 keys. Iteration took: 17.588284536s
badger 2020/02/08 13:26:24 DEBUG: LOG Compact. Added 1248393 keys. Skipped 7 keys. Iteration took: 4.083309515s
badger 2020/02/08 13:26:24 DEBUG: Discard stats: map[]
badger 2020/02/08 13:26:24 INFO: LOG Compact 0->1, del 7 tables, add 3 tables, took 39.706467279s
badger 2020/02/08 13:26:24 INFO: Compaction for level: 0 DONE
badger 2020/02/08 13:26:24 INFO: Got compaction priority: {level:0 score:1 dropPrefix:[]}
badger 2020/02/08 13:26:24 INFO: Running for level: 0
badger 2020/02/08 13:26:41 DEBUG: LOG Compact. Added 5228631 keys. Skipped 174 keys. Iteration took: 16.808560075s
badger 2020/02/08 13:26:58 DEBUG: LOG Compact. Added 5228104 keys. Skipped 191 keys. Iteration took: 16.897105465s
badger 2020/02/08 13:27:15 DEBUG: LOG Compact. Added 5229283 keys. Skipped 147 keys. Iteration took: 16.762568498s
badger 2020/02/08 13:27:21 DEBUG: LOG Compact. Added 1796104 keys. Skipped 62 keys. Iteration took: 5.826918105s
badger 2020/02/08 13:27:21 DEBUG: Discard stats: map[]
badger 2020/02/08 13:27:21 INFO: LOG Compact 0->1, del 8 tables, add 4 tables, took 56.444711036s
badger 2020/02/08 13:27:21 INFO: Compaction for level: 0 DONE
badger 2020/02/08 13:27:21 DEBUG: Storing value log head: {Fid:19 Len:32 Offset:29215840}
badger 2020/02/08 13:27:21 DEBUG: Flushing memtable, mt.size=67598483 size of flushChan: 5
took 65.99 sec  15153 writes/sec
badger 2020/02/08 13:27:24 DEBUG: Storing value log head: {Fid:20 Len:32 Offset:34432671}
badger 2020/02/08 13:27:24 DEBUG: Flushing memtable, mt.size=67603801 size of flushChan: 5
```

setting opts.ZSTDCompressionLevel = 0  solves the problem

**Comment by jarifibrahim** [comment]
@gladkikhartem Compression is a CPU intensive task and we stall writes if there are too many tables in the memory. Badger v2.0.2 was using ZSTD compression Level 15 which is super slow. We recently decided to disable compression by default https://github.com/dgraph-io/badger/pull/1191.

I suggest you disable the compression (set compression to options.None) or use level 1 to 3 compression level. 

We will soon be releasing badger 2.0.2 which would have compression disabled by default.

**Comment by jarifibrahim** [comment]
On a side note, you can use `WriteBatch` to bulk load data. `WriteBatch` is much faster than using transactions.
