### ISSUE TITLE
Badger throws nil pointer exception

### ISSUE THREAD

**Issue by mangalaman93** [dgraph-io/badger#1237]
```
alpha2    | E0302 20:49:47.266784       1 mutation.go:187] error in updating schema, aborting :: Writes are blocked, possibly due to DropAll or Close
alpha2    | panic: runtime error: invalid memory address or nil pointer dereference
alpha2    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x10eea0a]
alpha2    | 
alpha2    | goroutine 373339 [running]:
alpha2    | github.com/dgraph-io/badger/v2/skl.(*Skiplist).IncrRef(...)
alpha2    | 	/home/aman/gocode/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-0.20191220102048-ab4352b00a17/skl/skl.go:86
alpha2    | github.com/dgraph-io/badger/v2.(*DB).getMemTables(0xc0000dc400, 0x0, 0x0, 0x0, 0x0)
alpha2    | 	/home/aman/gocode/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-0.20191220102048-ab4352b00a17/db.go:542 +0xea
alpha2    | github.com/dgraph-io/badger/v2.(*DB).get(0xc0000dc400, 0xc05df8fc60, 0x18, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
alpha2    | 	/home/aman/gocode/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-0.20191220102048-ab4352b00a17/db.go:574 +0x66
alpha2    | github.com/dgraph-io/badger/v2.(*Txn).Get(0xc05f32e080, 0xc05df81f00, 0x10, 0x10, 0xc05df81f00, 0x10, 0x10)
alpha2    | 	/home/aman/gocode/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-0.20191220102048-ab4352b00a17/txn.go:407 +0xe7
alpha2    | github.com/dgraph-io/dgraph/schema.Load(0xc0276c2180, 0xd, 0x0, 0x0)
alpha2    | 	/home/aman/gocode/src/github.com/dgraph-io/dgraph/schema/schema.go:402 +0x12d
alpha2    | github.com/dgraph-io/dgraph/worker.runSchemaMutation.func1.1.1(0x0, 0x0)
alpha2    | 	/home/aman/gocode/src/github.com/dgraph-io/dgraph/worker/mutation.go:173 +0x36
alpha2    | github.com/dgraph-io/dgraph/x.RetryUntilSuccess(0xa, 0x989680, 0xc026eb1ec8, 0xc04f109d50, 0x238879f)
alpha2    | 	/home/aman/gocode/src/github.com/dgraph-io/dgraph/x/x.go:399 +0x51
alpha2    | github.com/dgraph-io/dgraph/worker.runSchemaMutation.func1.1(0xc026eb1f4f, 0xc0430e3810)
alpha2    | 	/home/aman/gocode/src/github.com/dgraph-io/dgraph/worker/mutation.go:172 +0x73
alpha2    | github.com/dgraph-io/dgraph/worker.runSchemaMutation.func1(0xc0430e3810, 0xc041107110)
alpha2    | 	/home/aman/gocode/src/github.com/dgraph-io/dgraph/worker/mutation.go:188 +0x21d
alpha2    | created by github.com/dgraph-io/dgraph/worker.runSchemaMutation
alpha2    | 	/home/aman/gocode/src/github.com/dgraph-io/dgraph/worker/mutation.go:164 +0x443
alpha3 exited with code 137
alpha1    | W0302 20
```

**Comment by jarifibrahim** [comment]
@mangalaman93 This looks similar to the DB Close we had before. Can you check if this error shows up only while closing the DB?

**Comment by jarifibrahim** [comment]
The nil pointer exception was thrown when the following code was running. 
```
loadErr := x.RetryUntilSuccess(maxRetries, 10*time.Millisecond, func() error {
	return schema.Load(update.Predicate)
})
```
from https://github.com/dgraph-io/dgraph/blob/0e3c4b0d20aa5ec479ac2dc8f461999a03fe838d/worker/mutation.go#L124-L126

It might be possible that the badger instance running in Dgraph was closed while the retries were in progress. This would mean the GET operation was performed on a closed DB and there would be a nil pointer panic. 

Related to https://github.com/dgraph-io/dgraph/issues/3873

Closing this issue as invalid.
