### ISSUE TITLE
[Release Blocker] Sigbus error in block iterator

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/badger#1318]
Copied over from https://sentry.io/organizations/dgraph/issues/1620931878
Affected badger version `v2.0.1-rc1.0.20200421062606-cddf7c03451c` commit cddf7c03451c
The failure looks similar to https://github.com/dgraph-io/badger/pull/1150 where we were trying to read beyond the actual size of an mmap file.
```
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f6ae032542e pc=0xd8eddc]

goroutine 175 [running]:
runtime.throw(0x19405e6, 0x5)
	/usr/local/go/src/runtime/panic.go:1114 +0x72 fp=0xc0005f4ab8 sp=0xc0005f4a88 pc=0x9815d2
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:692 +0x443 fp=0xc0005f4ae8 sp=0xc0005f4ab8 pc=0x998f23
github.com/dgraph-io/badger/v2/table.(*blockIterator).setIdx(0xc00665bd50, 0x0)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/table/iterator.go:62 +0xbc fp=0xc0005f4b90 sp=0xc0005f4ae8 pc=0xd8eddc
github.com/dgraph-io/badger/v2/table.(*blockIterator).seekToFirst(...)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/table/iterator.go:137
github.com/dgraph-io/badger/v2/table.(*Iterator).next(0xc00665bd40)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/table/iterator.go:303 +0x1bd fp=0xc0005f4bd8 sp=0xc0005f4b90 pc=0xd8fffd
github.com/dgraph-io/badger/v2/table.(*Table).NewIterator(0xc00025c000, 0x8050149ca1c6c300, 0x0)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/table/iterator.go:169 +0x6b fp=0xc0005f4c00 sp=0xc0005f4bd8 pc=0xd8f44b
github.com/dgraph-io/badger/v2.(*levelHandler).get(0xc00050a420, 0xc006794460, 0x14, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/level_handler.go:271 +0x19e fp=0xc0005f4cc0 sp=0xc0005f4c00 pc=0xdb28fe
github.com/dgraph-io/badger/v2.(*levelsController).get(0xc000172070, 0xc006794460, 0x14, 0x14, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/levels.go:988 +0xcf fp=0xc0005f4da0 sp=0xc0005f4cc0 pc=0xdbb78f
github.com/dgraph-io/badger/v2.(*DB).RunValueLogGC(0xc00016c800, 0x3fe6666666666666, 0x193e366, 0x2)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/db.go:1174 +0x118 fp=0xc0005f4e68 sp=0xc0005f4da0 pc=0xda6388
github.com/dgraph-io/dgraph/x.RunVlogGC.func1()
	/ext-go/1/src/github.com/dgraph-io/dgraph/x/x.go:894 +0x4a fp=0xc0005f4ea8 sp=0xc0005f4e68 pc=0x114cc7a
github.com/dgraph-io/dgraph/x.RunVlogGC(0xc00016c800, 0xc00000fac0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/x/x.go:910 +0x219 fp=0xc0005f4fd0 sp=0xc0005f4ea8 pc=0x114bf79
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0005f4fd8 sp=0xc0005f4fd0 pc=0x9b4de1
created by github.com/dgraph-io/dgraph/dgraph/cmd/zero.run
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/run.go:231 +0x9c1

goroutine 1 [semacquire, 10 minutes]:
sync.runtime_Semacquire(0xc00050c2f0)
	/usr/local/go/src/runtime/sema.go:56 +0x42
sync.(*WaitGroup).Wait(0xc00050c2e8)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/dgraph-io/badger/v2/y.(*Closer).Wait(...)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/y/y.go:234
github.com/dgraph-io/dgraph/dgraph/cmd/zero.run()
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/run.go:308 +0x1045
github.com/dgraph-io/dgraph/dgraph/cmd/zero.init.0.func1(0xc000568000, 0x282e510, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/run.go:76 +0x62
github.com/spf13/cobra.(*Command).execute(0xc000568000, 0x282e510, 0x0, 0x0, 0xc000568000, 0x282e510)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x26125e0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/dgraph-io/dgraph/dgraph/cmd.Execute()
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:70 +0x80
main.main()
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/main.go:78 +0xb0

goroutine 19 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x2803240)
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x26f

goroutine 21 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000140a50)
	/go/pkg/mod/go.opencensus.io@v0.21.0/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/go/pkg/mod/go.opencensus.io@v0.21.0/stats/view/worker.go:32 +0x57

goroutine 22 [chan receive]:
github.com/dgraph-io/dgraph/x.init.0.func1(0x1b747a0, 0xc000134010)
	/ext-go/1/src/github.com/dgraph-io/dgraph/x/metrics.go:212 +0xde
created by github.com/dgraph-io/dgraph/x.init.0
	/ext-go/1/src/github.com/dgraph-io/dgraph/x/metrics.go:208 +0x93

goroutine 38 [chan receive]:
main.main.func1()
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/main.go:46 +0xf8
created by main.main
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/main.go:37 +0xab

goroutine 39 [chan receive, 10 minutes]:
github.com/getsentry/sentry-go.(*HTTPTransport).worker(0xc0001720e0)
	/go/pkg/mod/github.com/getsentry/sentry-go@v0.5.1/transport.go:303 +0x7a
created by github.com/getsentry/sentry-go.(*HTTPTransport).Configure.func1
	/go/pkg/mod/github.com/getsentry/sentry-go@v0.5.1/transport.go:174 +0x3e

goroutine 7 [select]:
github.com/dgraph-io/badger/v2/y.(*WaterMark).process(0xc0005d41b0, 0xc00012e0e0)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/y/watermark.go:212 +0x2c5
created by github.com/dgraph-io/badger/v2/y.(*WaterMark).Init
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/y/watermark.go:70 +0x7a

goroutine 8 [select, 3 minutes]:
github.com/dgraph-io/badger/v2/y.(*WaterMark).process(0xc0005d41e0, 0xc00012e0e0)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/y/watermark.go:212 +0x2c5
created by github.com/dgraph-io/badger/v2/y.(*WaterMark).Init
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/y/watermark.go:70 +0x7a

goroutine 154 [select, 10 minutes]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00011f830)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2-0.20200115201040-8f368f2f2ab3/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2-0.20200115201040-8f368f2f2ab3/policy.go:80 +0x129

goroutine 155 [select, 10 minutes]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc00064e4e0)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2-0.20200115201040-8f368f2f2ab3/cache.go:269 +0xbc
created by github.com/dgraph-io/ristretto.NewCache
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2-0.20200115201040-8f368f2f2ab3/cache.go:155 +0x1f3

goroutine 156 [select]:
github.com/dgraph-io/badger/v2.(*DB).updateSize(0xc00016c800, 0xc00000f680)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/db.go:1119 +0x149
created by github.com/dgraph-io/badger/v2.Open
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/db.go:341 +0x95c

goroutine 167 [select]:
github.com/dgraph-io/badger/v2.(*levelsController).runWorker(0xc000172070, 0xc00000f800)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/levels.go:359 +0x20c
created by github.com/dgraph-io/badger/v2.(*levelsController).startCompact
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/levels.go:340 +0x88

goroutine 168 [select]:
github.com/dgraph-io/badger/v2.(*levelsController).runWorker(0xc000172070, 0xc00000f800)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/levels.go:359 +0x20c
created by github.com/dgraph-io/badger/v2.(*levelsController).startCompact
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/levels.go:340 +0x88

goroutine 169 [chan receive, 10 minutes]:
github.com/dgraph-io/badger/v2.(*DB).flushMemtable(0xc00016c800, 0xc00000f820, 0x0, 0x0)
	/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200421062606-cddf7c03451c/db.go:1026 +0xb7
github.com/dgraph-i... 
```

**Comment by jarifibrahim** [comment]
This issue is not reproducible. I'll reopen the issue if it shows up again.
