### ISSUE TITLE
Close db will cause panic if read badger in another goroutine.

### ISSUE THREAD

**Issue by cedricfung** [dgraph-io/badger#1360]
### What version of Go are you using (`go version`)?

<pre>
$ go version

go version go1.14.1 linux/amd64
</pre>

### What operating system are you using?

Ubuntu 20.04

### What version of Badger are you using?

v2.0.3

### Does this issue reproduce with the latest master?

Not tested yet.

### Steps to Reproduce the issue

I'm running a test in my code, the test uses badger in goroutines, and the test will close the db in main routine. I think badger is thread safe, so close the db should not cause panic in another goroutine.

### What Badger options were set? 

```golang
	opts := badger.DefaultOptions(dir)
	opts = opts.WithSyncWrites(sync)
	opts = opts.WithCompression(options.None)
	opts = opts.WithMaxCacheSize(0)
	db, err := badger.Open(opts)
```

### What did you do?

Get the latest master of https://github.com/MixinNetwork/mixin and run test.

```
go test github.com/MixinNetwork/mixin/rpc -run TestA -count 1
```

### What did you expect to see?

No badger related crashes.

### What did you see instead?

Sometimes the test passes, but sometimes it panics. 

The `badger_node.go:107` code is `it := txn.NewIterator(badger.DefaultIteratorOptions)`. I can't figure out why NewIterator would cause these panics.

```
=== RUN   TestAllTransactionsToSingleGenesisNode
badger 2020/06/10 18:36:29 INFO: All 0 tables opened in 0s
panic: runtime error: invalid memory address or nil pointer dereference
	panic: Unclosed iterator at time of Txn.Discard.
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9aa041]

goroutine 5581 [running]:
github.com/dgraph-io/badger/v2.(*Txn).Discard(0xc0fa3eb680)
	/Code/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/txn.go:448 +0xdd
panic(0xbff480, 0x13b0040)
	/usr/local/go/src/runtime/panic.go:967 +0x166
github.com/dgraph-io/badger/v2/skl.(*Skiplist).IncrRef(...)
	/Code/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/skl/skl.go:86
github.com/dgraph-io/badger/v2.(*DB).getMemTables(0xc0002b6900, 0x0, 0x0, 0x0, 0x0)
	/Code/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/db.go:578 +0xd1
github.com/dgraph-io/badger/v2.(*Txn).NewIterator(0xc0fa3eb680, 0x1, 0x64, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Code/GOPATH/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/iterator.go:458 +0x89
github.com/MixinNetwork/mixin/storage.readNodesInState(0xc0fa3eb680, 0xcc87ea, 0xf, 0x0, 0x0, 0x0)
	/Code/github.com/kernel/storage/badger_node.go:107 +0x9d
github.com/MixinNetwork/mixin/storage.(*BadgerStore).ReadConsensusNodes(0xc00032bd10, 0x0, 0x0, 0x0)
	/Code/github.com/kernel/storage/badger_node.go:30 +0xdb
github.com/MixinNetwork/mixin/storage.(*BadgerStore).ReadAllNodes(0xc00032bd10, 0x0, 0x0, 0x0)
	/Code/github.com/kernel/storage/badger_validation.go:130 +0xac
github.com/MixinNetwork/mixin/kernel.(*Node).ReadAllNodes(0xc0002b2400, 0xc1388a5800, 0x8, 0x8)
	/Code/github.com/kernel/kernel/node.go:359 +0x52
github.com/MixinNetwork/mixin/network.(*Peer).syncToNeighborLoop(0xc00ac98820, 0xc0002bb7c0)
	/Code/github.com/kernel/network/sync.go:152 +0x432
created by github.com/MixinNetwork/mixin/network.(*Peer).AddNeighbor
	/Code/github.com/kernel/network/peer.go:102 +0x31a
FAIL	github.com/MixinNetwork/mixin/rpc	11.863s
FAIL
```

**Comment by cedricfung** [comment]
my code has
