### ISSUE TITLE
Crash during compaction

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/badger#238]
Ran into this while attempting to load the graph overflow dataset (2 billion edges). Occurred right at the end (I *think* when attempting to close the badgers).

Version: 64df7f57d9ee20d7b28de4a3eea90bf8d7310a77

Settings:

```
 52     opt := badger.DefaultOptions
 53     opt.ValueGCRunInterval = time.Hour * 100
 54     opt.SyncWrites = false
 55     opt.TableLoadingMode = bo.MemoryMap
 56     opt.Dir = s.opt.shardOutputDirs[i]
 57     opt.ValueDir = opt.Dir
```

```
panic: runtime error: slice bounds out of range

goroutine 10952 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.(*blockIterator).parseKV(0xdc8cdb50e0, 0x16a017000c, 0x572)
        /home/ec2-user/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/iterator.go:115 +0x54c
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.(*blockIterator).Next(0xdc8cdb50e0)
        /home/ec2-user/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/iterator.go:153 +0x1e5
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.(*Iterator).next(0xd1041b23c0)
        /home/ec2-user/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/iterator.go:346 +0xb9
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.(*Iterator).Next(0xd1041b23c0)
        /home/ec2-user/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/iterator.go:396 +0x46
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.(*MergeIterator).Next(0xcba305a140)
        /home/ec2-user/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/iterator.go:202 +0x54
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).compactBuildTables(0xc420158000, 0x0, 0x1211b60, 0xd81985c4e0, 0xc72f88e000, 0xc72f88e060, 0xd1041b2270, 0x5, 0x5, 0xdf39cab870, ...)
        /home/ec2-user/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:293 +0x33c
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).runCompactDef(0xc420158000, 0x0, 0x1211b60, 0xd81985c4e0, 0xc72f88e000, 0xc72f88e060, 0xd1041b2270, 0x5, 0x5, 0xdf39cab870, ...)
        /home/ec2-user/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:526 +0xfb
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).doCompact(0xc420158000, 0x0, 0x3ff0000000000000, 0x0, 0x0, 0x0)
        /home/ec2-user/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:592 +0x3df
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).runWorker(0xc420158000, 0xc4201d0160)
        /home/ec2-user/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:199 +0x120
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*levelsController).startCompact
        /home/ec2-user/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:178 +0x82
```

**Comment by srh** [comment]
I also noticed that getTestOptions, if you set SyncWrites = false, you get

```
--- FAIL: TestValueBasic (0.87s)
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 78796 [running]:
testing.tRunner.func1(0xc4201261e0)
	/usr/local/go/src/testing/testing.go:711 +0x2d2
panic(0x7ebfa0, 0xa8ac80)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/dgraph-io/badger.(*header).Decode(...)
	/home/srh/go/src/github.com/dgraph-io/badger/value.go:528
github.com/dgraph-io/badger.valueBytesToEntry(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/srh/go/src/github.com/dgraph-io/badger/value.go:933 +0x1c4
github.com/dgraph-io/badger.TestValueBasic(0xc4201261e0)
	/home/srh/go/src/github.com/dgraph-io/badger/value_test.go:76 +0x882
testing.tRunner(0xc4201261e0, 0x879388)
	/usr/local/go/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x2de
```

the very first time I run it.

The line of code I changed was originally

`	opt.SyncWrites = false // Some tests seem to need this to pass.`

Well, it's not the same bug, but it might be that by setting SyncWrites=false you're triggering some race condition that doesn't normally get triggered.

**Comment by deepakjois** [comment]
Too many changes have happened since this, and nobody seems to have reported anything similar. I am going to close this for now.
