### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by cryptix** [dgraph-io/badger#278]
Hi,

I made a tool that dumps messages from another db into badger to test some usecases and assumptions but I was thrown off by panics like these:

```
goroutine 513 [running]:
github.com/dgraph-io/badger.(*DB).sendToWriteCh(0xc42019c000, 0xc425aec6e0, 0x2, 0x2, 0xc425c03a40, 0x412738, 0x40)
        /home/user/go/src/github.com/dgraph-io/badger/db.go:643 +0x169
github.com/dgraph-io/badger.(*DB).batchSet(0xc42019c000, 0xc425aec6e0, 0x2, 0x2, 0x5, 0x8)
        /home/user/go/src/github.com/dgraph-io/badger/db.go:653 +0x4d
github.com/dgraph-io/badger.(*Txn).Commit(0xc420182300, 0x0, 0x0, 0x0)
        /home/user/go/src/github.com/dgraph-io/badger/transaction.go:358 +0x714
github.com/dgraph-io/badger.(*DB).Update(0xc42019c000, 0xc425c03c10, 0x0, 0x0)
        /home/user/go/src/github.com/dgraph-io/badger/transaction.go:432 +0x160
cryptoscope.co/go/panopticon.(*Store).Put(0xc420096280, 0xc420018600, 0x3a, 0x3a, 0xc42001e540, 0x1bc, 0x1bc, 0x0, 0x0)
        /home/user/go/src/cryptoscope.co/go/panopticon/store.go:102 +0xb4
...
```

I guess [these Put()](https://github.com/keks/panopticon/blob/master/store.go#L103)s are batched to tightly? I would have assumed degraded performance over panics though...

**Comment by manishrjain** [comment]
This panic is happening because writeCh is closed, which happens if you close the DB, and do writes afterwards.

**Comment by cryptix** [comment]
sorry about the noise. the wait channel for the put's was used incorrectly.
panics are gone now. thanks.

**Comment by dhaavi** [comment]
I think I just came across the same error: a `send on closed channel` panic after the database was closed.

But shouldn't this return an error as stated in issue #420?

Here is my stack trace:
```
panic: send on closed channel

goroutine 156 [running]:
github.com/dgraph-io/badger.(*DB).sendToWriteCh(0xc000478000, 0xc0000a3780, 0x2, 0x2, 0x2, 0x8, 0x13)
	/home/user/go/src/github.com/dgraph-io/badger/db.go:651 +0x161
github.com/dgraph-io/badger.(*Txn).commitAndSend(0xc000404280, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/dgraph-io/badger/txn.go:539 +0x461
github.com/dgraph-io/badger.(*Txn).Commit(0xc000404280, 0x0, 0x0)
	/home/user/go/src/github.com/dgraph-io/badger/txn.go:590 +0x8b
github.com/dgraph-io/badger.(*DB).Update(0xc000478000, 0xc0003ebe28, 0x0, 0x0)
	/home/user/go/src/github.com/dgraph-io/badger/txn.go:744 +0xbc
github.com/Safing/portbase/database/storage/badger.(*Badger).Put(0xc000432200, 0xd968e0, 0xc0000bc4c0, 0xd968e0, 0xc0000bc4c0)
	/home/user/go/src/github.com/Safing/portbase/database/storage/badger/badger.go:86 +0xe3
github.com/Safing/portbase/database.(*Controller).Put(0xc000252080, 0xd968e0, 0xc0000bc4c0, 0x0, 0x0)
	/home/user/go/src/github.com/Safing/portbase/database/controller.go:122 +0x234
github.com/Safing/portbase/database.(*Interface).Put(0xc0000ae3a0, 0xd968e0, 0xc0000bc4c0, 0x0, 0x0)
	/home/user/go/src/github.com/Safing/portbase/database/interface.go:185 +0x209
github.com/Safing/portmaster/updates.(*versionStatus).save(0xc0000bc4c0)
	/home/user/go/src/github.com/Safing/portmaster/updates/status.go:56 +0x56
created by github.com/Safing/portmaster/updates.updateStatus
	/home/user/go/src/github.com/Safing/portmaster/updates/status.go:109 +0x296
```
