### ISSUE TITLE
Transaction set(key, value) no response.

### ISSUE THREAD

**Issue by blueCao** [dgraph-io/badger#407]
### I am try to write 1.5 Billions records by 32 writing-transaction threads with each value is 100 bytes(fill with 1) and the key is just the number from 1 to 1.5 billion . When the badger DB directory size is comming up about 286G, the program was sleeping without any response (the DB size didn't change and the console didn't alert error). 

- here is [my badger writing-test code ](https://github.com/blueCao/badger/blob/master/badger-write-test.go)
-  the last 5 vlog records is showing bellow:
```
?!badger!txn??????X?1346807665??ud@1346807664??????X?1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111r?&
?!badger!txn??????X?1346807666??C3d@1346807667??????X?1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111????
?!badger!txn??????X?1346807667մ7?d@1346807668??????X?1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111?F?(
?!badger!txn??????X?1346807668a?W?d@1346807669??????X?1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111?b?l
?!badger!txn??????X?1346807669?#C
```

**Comment by funny-falcon** [comment]
Probably I also were caught with this.
I didn't count number of rows, but looks like there is some accidential limit: i was able to insert "a bit lesser", but when other time I tried to insert a bit more, it stuck.

**Comment by manishrjain** [comment]
How long did it take to fill up 286G? Possible to reproduce this in a smaller setup?

**Comment by funny-falcon** [comment]
I put ~4kb values, and ~70b keys, and stalled at about 220GB.
Though size looks similar, i thing it is more tangled with lsm size than with vlog size. Though I could be mistaken.

**Comment by manishrjain** [comment]
This particular goroutine is causing a stall.

```
goroutine 11 [sleep]:
time.Sleep(0x989680)
	/usr/lib/go-1.8/src/runtime/time.go:59 +0xf9
github.com/dgraph-io/badger.(*levelsController).addLevel0Table(0xc425498000, 0xc457b95ce0, 0xc457b95ce0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/levels.go:636 +0x498
github.com/dgraph-io/badger.(*DB).flushMemtable(0xc420114600, 0xc42000c3c0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/db.go:809 +0x375
created by github.com/dgraph-io/badger.Open
	/home/mrjn/go/src/github.com/dgraph-io/badger/db.go:263 +0x9bf
```

This is a for loop, which is constantly checking this:

```
		for {
			// Passing 0 for delSize to compactable means we're treating incomplete compactions as
			// not having finished -- we wait for them to finish.  Also, it's crucial this behavior
			// replicates pickCompactLevels' behavior in computing compactability in order to
			// guarantee progress.
			if !s.isLevel0Compactable() && !s.levels[1].isCompactable(0) {
				break
			}
			time.Sleep(10 * time.Millisecond)
		}
```

For some reason, level 0 and level 1 are both not considered compactable, despite the fact that no other compaction is going on. So, we're stuck infinitely waiting here.

**Comment by manishrjain** [comment]
It also seems a bit weird that flushMemtable goroutine can be returned and exited. And I don't see any way to bring it back.

https://github.com/dgraph-io/badger/blob/8d041dd05458b8c3a85eefcae81952933ef3f72e/db.go#L761

@janardhan1993 : Can you also have a look at `flushMemtable` and see if these returns should be either removed or cause a DB wide error? FWIW, this particular issue isn't being caused by a return here. So, this is a tangential enquiry.

**Comment by manishrjain** [comment]
```
goroutine 908218 [running]:
runtime/pprof.writeGoroutineStacks(0xa5fd80, 0xc43f4340e0, 0x30, 0xc429644030)
	/usr/lib/go-1.8/src/runtime/pprof/pprof.go:603 +0x79
runtime/pprof.writeGoroutine(0xa5fd80, 0xc43f4340e0, 0xa, 0xc429059a90, 0x4116c8)
	/usr/lib/go-1.8/src/runtime/pprof/pprof.go:592 +0x44
runtime/pprof.(*Profile).WriteTo(0xa8b6e0, 0xa5fd80, 0xc43f4340e0, 0xa, 0xc43f4340e0, 0xc429059cc0)
	/usr/lib/go-1.8/src/runtime/pprof/pprof.go:302 +0x3b5
net/http/pprof.handler.ServeHTTP(0xc42989d7e1, 0x9, 0xa645c0, 0xc43f4340e0, 0xc42000aa00)
	/usr/lib/go-1.8/src/net/http/pprof/pprof.go:209 +0x1d1
net/http/pprof.Index(0xa645c0, 0xc43f4340e0, 0xc42000aa00)
	/usr/lib/go-1.8/src/net/http/pprof/pprof.go:221 +0x1e3
net/http.HandlerFunc.ServeHTTP(0x8a09c8, 0xa645c0, 0xc43f4340e0, 0xc42000aa00)
	/usr/lib/go-1.8/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xa977e0, 0xa645c0, 0xc43f4340e0, 0xc42000aa00)
	/usr/lib/go-1.8/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc42562a000, 0xa645c0, 0xc43f4340e0, 0xc42000aa00)
	/usr/lib/go-1.8/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4769460a0, 0xa64e40, 0xc42bc6aa40)
	/usr/lib/go-1.8/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce

goroutine 1 [semacquire, 81 minutes]:
sync.runtime_Semacquire(0xc4254961ec)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4254961e0)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
main.main()
	/home/mrjn/go/src/populate/main.go:184 +0x4b3

goroutine 17 [syscall, 81 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

goroutine 6 [syscall, 81 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/go-1.8/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/lib/go-1.8/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/lib/go-1.8/src/os/signal/signal_unix.go:28 +0x41

goroutine 7 [select, 2 minutes]:
github.com/dgraph-io/badger.(*DB).updateSize(0xc420114600, 0xc4200c1b20)
	/home/mrjn/go/src/github.com/dgraph-io/badger/db.go:882 +0x183
created by github.com/dgraph-io/badger.Open
	/home/mrjn/go/src/github.com/dgraph-io/badger/db.go:251 +0x81d

goroutine 8 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc425498000, 0xc42000c380)
	/home/mrjn/go/src/github.com/dgraph-io/badger/levels.go:187 +0x222
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/home/mrjn/go/src/github.com/dgraph-io/badger/levels.go:172 +0x8a

goroutine 9 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc425498000, 0xc42000c380)
	/home/mrjn/go/src/github.com/dgraph-io/badger/levels.go:187 +0x222
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/home/mrjn/go/src/github.com/dgraph-io/badger/levels.go:172 +0x8a

goroutine 10 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc425498000, 0xc42000c380)
	/home/mrjn/go/src/github.com/dgraph-io/badger/levels.go:187 +0x222
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/home/mrjn/go/src/github.com/dgraph-io/badger/levels.go:172 +0x8a

goroutine 11 [sleep]:
time.Sleep(0x989680)
	/usr/lib/go-1.8/src/runtime/time.go:59 +0xf9
github.com/dgraph-io/badger.(*levelsController).addLevel0Table(0xc425498000, 0xc457b95ce0, 0xc457b95ce0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/levels.go:636 +0x498
github.com/dgraph-io/badger.(*DB).flushMemtable(0xc420114600, 0xc42000c3c0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/db.go:809 +0x375
created by github.com/dgraph-io/badger.Open
	/home/mrjn/go/src/github.com/dgraph-io/badger/db.go:263 +0x9bf

goroutine 13 [select, 20 minutes]:
github.com/dgraph-io/badger.(*DB).doWrites(0xc420114600, 0xc4254944c0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/db.go:645 +0x67f
created by github.com/dgraph-io/badger.Open
	/home/mrjn/go/src/github.com/dgraph-io/badger/db.go:307 +0xe20

goroutine 14 [chan receive, 81 minutes]:
github.com/dgraph-io/badger.(*valueLog).waitOnGC(0xc420114730, 0xc4254944e0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:1031 +0x6d
created by github.com/dgraph-io/badger.Open
	/home/mrjn/go/src/github.com/dgraph-io/badger/db.go:310 +0xe86

goroutine 15 [select]:
main.main.func2(0xc420120080, 0xc4254961c0, 0xa64e40, 0xc4201200c0)
	/home/mrjn/go/src/populate/main.go:139 +0x2d6
created by main.main
	/home/mrjn/go/src/populate/main.go:150 +0x3c5

goroutine 16 [IO wait]:
net.runtime_pollWait(0x7f660f2b7fa0, 0x72, 0x0)
	/usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420010228, 0x72, 0x0, 0xc4e8a21c60)
	/usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420010228, 0xffffffffffffffff, 0x0)
	/usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4200101c0, 0x0, 0xa60000, 0xc4e8a21c60)
	/usr/lib/go-1.8/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc42549a000, 0xc4200d06c0, 0x802380, 0xffffffffffffffff)
	/usr/lib/go-1.8/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42549a000, 0xc4255b7e70, 0xc4255b7e78, 0xc4255b7e68)
	/usr/lib/go-1.8/src/net/tcpsock.go:215 +0x49
net/http.tcpKeepAliveListener.Accept(0xc42549a000, 0x8a0810, 0xc4200d0640, 0xa64f00, 0xc4200173b0)
	/usr/lib/go-1.8/src/net/http/server.go:3044 +0x2f
net/http.(*Server).Serve(0xc42562a000, 0xa64880, 0xc42549a000, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/http/server.go:2643 +0x228
net/http.(*Server).ListenAndServe(0xc42562a000, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/http/server.go:2585 +0xb0
net/http.ListenAndServe(0x888313, 0xc, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/http/server.go:2787 +0x7f
main.main.func3()
	/home/mrjn/go/src/populate/main.go:152 +0x4c
created by main.main
	/home/mrjn/go/src/populate/main.go:155 +0x3dd

goroutine 50 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc42912743c)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc429127430)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger.(*request).Wait(0xc429127400, 0x89ff40, 0xc42001b080)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc457bed050, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:481 +0x7a9
main.writeBatch(0xc4255c2060, 0x3e8, 0x3e8, 0x3e8)
	/home/mrjn/go/src/populate/main.go:66 +0x125
main.main.func4(0x4197d78400000000, 0xc, 0xc4254961c0, 0xc420120080, 0xc4254961e0, 0x0)
	/home/mrjn/go/src/populate/main.go:172 +0x196
created by main.main
	/home/mrjn/go/src/populate/main.go:181 +0x484

goroutine 51 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc4e8ab1c5c)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4e8ab1c50)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger.(*request).Wait(0xc4e8ab1c20, 0x89ff40, 0xc42001b080)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc4a777eab0, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:481 +0x7a9
main.writeBatch(0xc4255ca060, 0x3e8, 0x3e8, 0x3e8)
	/home/mrjn/go/src/populate/main.go:66 +0x125
main.main.func4(0x4197d78400000000, 0xc, 0xc4254961c0, 0xc420120080, 0xc4254961e0, 0x1)
	/home/mrjn/go/src/populate/main.go:172 +0x196
created by main.main
	/home/mrjn/go/src/populate/main.go:181 +0x484

goroutine 52 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc460d5c99c)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc460d5c990)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger.(*request).Wait(0xc460d5c960, 0x89ff40, 0xc42001b080)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc499dca240, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:481 +0x7a9
main.writeBatch(0xc425626060, 0x3e8, 0x3e8, 0x3e8)
	/home/mrjn/go/src/populate/main.go:66 +0x125
main.main.func4(0x4197d78400000000, 0xc, 0xc4254961c0, 0xc420120080, 0xc4254961e0, 0x2)
	/home/mrjn/go/src/populate/main.go:172 +0x196
created by main.main
	/home/mrjn/go/src/populate/main.go:181 +0x484

goroutine 53 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc4e29b421c)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4e29b4210)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger.(*request).Wait(0xc4e29b41e0, 0x89ff40, 0xc42001b080)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc4e29d7050, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:481 +0x7a9
main.writeBatch(0xc4255ce060, 0x3e8, 0x3e8, 0x3e8)
	/home/mrjn/go/src/populate/main.go:66 +0x125
main.main.func4(0x4197d78400000000, 0xc, 0xc4254961c0, 0xc420120080, 0xc4254961e0, 0x3)
	/home/mrjn/go/src/populate/main.go:172 +0x196
created by main.main
	/home/mrjn/go/src/populate/main.go:181 +0x484

goroutine 54 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc49ae6408c)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc49ae64080)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger.(*request).Wait(0xc49ae64050, 0x89ff40, 0xc42001b080)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc451b08000, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:481 +0x7a9
main.writeBatch(0xc4255fe060, 0x3e8, 0x3e8, 0x3e8)
	/home/mrjn/go/src/populate/main.go:66 +0x125
main.main.func4(0x4197d78400000000, 0xc, 0xc4254961c0, 0xc420120080, 0xc4254961e0, 0x4)
	/home/mrjn/go/src/populate/main.go:172 +0x196
created by main.main
	/home/mrjn/go/src/populate/main.go:181 +0x484

goroutine 55 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc4291870cc)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4291870c0)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger.(*request).Wait(0xc429187090, 0x89ff40, 0xc42001b080)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc42a56a480, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:481 +0x7a9
main.writeBatch(0xc4255fa060, 0x3e8, 0x3e8, 0x3e8)
	/home/mrjn/go/src/populate/main.go:66 +0x125
main.main.func4(0x4197d78400000000, 0xc, 0xc4254961c0, 0xc420120080, 0xc4254961e0, 0x5)
	/home/mrjn/go/src/populate/main.go:172 +0x196
created by main.main
	/home/mrjn/go/src/populate/main.go:181 +0x484

goroutine 56 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc460a5462c)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc460a54620)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger.(*request).Wait(0xc460a545f0, 0x89ff40, 0xc42001b080)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc4f3c98360, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:481 +0x7a9
main.writeBatch(0xc425622060, 0x3e8, 0x3e8, 0x3e8)
	/home/mrjn/go/src/populate/main.go:66 +0x125
main.main.func4(0x4197d78400000000, 0xc, 0xc4254961c0, 0xc420120080, 0xc4254961e0, 0x6)
	/home/mrjn/go/src/populate/main.go:172 +0x196
created by main.main
	/home/mrjn/go/src/populate/main.go:181 +0x484

goroutine 57 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc49a1faf8c)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc49a1faf80)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger.(*request).Wait(0xc49a1faf50, 0x89ff40, 0xc42001b080)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc499d85680, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:481 +0x7a9
main.writeBatch(0xc4265fe060, 0x3e8, 0x3e8, 0x3e8)
	/home/mrjn/go/src/populate/main.go:66 +0x125
main.main.func4(0x4197d78400000000, 0xc, 0xc4254961c0, 0xc420120080, 0xc4254961e0, 0x7)
	/home/mrjn/go/src/populate/main.go:172 +0x196
created by main.main
	/home/mrjn/go/src/populate/main.go:181 +0x484

goroutine 58 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc4291d3edc)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4291d3ed0)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger.(*request).Wait(0xc4291d3ea0, 0x89ff40, 0xc42001b080)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc499dcb710, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:481 +0x7a9
main.writeBatch(0xc427200060, 0x3e8, 0x3e8, 0x3e8)
	/home/mrjn/go/src/populate/main.go:66 +0x125
main.main.func4(0x4197d78400000000, 0xc, 0xc4254961c0, 0xc420120080, 0xc4254961e0, 0x8)
	/home/mrjn/go/src/populate/main.go:172 +0x196
created by main.main
	/home/mrjn/go/src/populate/main.go:181 +0x484

goroutine 59 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc4287ca53c)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4287ca530)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger.(*request).Wait(0xc4287ca500, 0x89ff40, 0xc42001b080)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc451b09830, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:481 +0x7a9
main.writeBatch(0xc4265fa060, 0x3e8, 0x3e8, 0x3e8)
	/home/mrjn/go/src/populate/main.go:66 +0x125
main.main.func4(0x4197d78400000000, 0xc, 0xc4254961c0, 0xc420120080, 0xc4254961e0, 0x9)
	/home/mrjn/go/src/populate/main.go:172 +0x196
created by main.main
	/home/mrjn/go/src/populate/main.go:181 +0x484

goroutine 60 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc4606420dc)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4606420d0)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger.(*request).Wait(0xc4606420a0, 0x89ff40, 0xc42001b080)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc4296a2a20, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:481 +0x7a9
main.writeBatch(0xc427204060, 0x3e8, 0x3e8, 0x3e8)
	/home/mrjn/go/src/populate/main.go:66 +0x125
main.main.func4(0x4197d78400000000, 0xc, 0xc4254961c0, 0xc420120080, 0xc4254961e0, 0xa)
	/home/mrjn/go/src/populate/main.go:172 +0x196
created by main.main
	/home/mrjn/go/src/populate/main.go:181 +0x484

goroutine 61 [semacquire, 20 minutes]:
sync.runtime_Semacquire(0xc428f5dedc)
	/usr/lib/go-1.8/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc428f5ded0)
	/usr/lib/go-1.8/src/sync/waitgroup.go:131 +0x7a
github.com/dgraph-io/badger.(*request).Wait(0xc428f5dea0, 0x89ff40, 0xc42001b080)
	/home/mrjn/go/src/github.com/dgraph-io/badger/value.go:671 +0x35
github.com/dgraph-io/badger.(*Txn).Commit(0xc42a56bcb0, 0x0, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:481 +0x7a9
main.writeBatch(0xc4255c6060, 0x3e8, 0x3e8, 0x3e8)
	/home/mrjn/go/src/populate/main.go:66 +0x125
main.main.func4(0x4197d78400000000, 0xc, 0xc4254961c0, 0xc420120080, 0xc4254961e0, 0xb)
	/home/mrjn/go/src/populate/main.go:172 +0x196
created by main.main
	/home/mrjn/go/src/populate/main.go:181 +0x484

goroutine 908006 [IO wait, 16 minutes]:
net.runtime_pollWait(0x7f660f2b7e20, 0x72, 0x4a)
	/usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420116068, 0x72, 0xa61380, 0xa5d638)
	/usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420116068, 0xc4a5afc000, 0x1000)
	/usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420116000, 0xc4a5afc000, 0x1000, 0x1000, 0x0, 0xa61380, 0xa5d638)
	/usr/lib/go-1.8/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42bcde028, 0xc4a5afc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/net.go:181 +0x70
net/http.(*connReader).Read(0xc4f3cdf780, 0xc4a5afc000, 0x1000, 0x1000, 0x0, 0x2, 0x0)
	/usr/lib/go-1.8/src/net/http/server.go:754 +0x140
bufio.(*Reader).fill(0xc429144180)
	/usr/lib/go-1.8/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadSlice(0xc429144180, 0xa, 0x2, 0x0, 0x51ec97, 0xc4a5afd073, 0xa5d288)
	/usr/lib/go-1.8/src/bufio/bufio.go:338 +0xbb
bufio.(*Reader).ReadLine(0xc429144180, 0xc42547f100, 0x100, 0xf8, 0x8774e0, 0xc42002ac00, 0x7f660f3d44b0)
	/usr/lib/go-1.8/src/bufio/bufio.go:367 +0x37
net/textproto.(*Reader).readLineSlice(0xc4939cc960, 0xc429055ac8, 0xc429055ac8, 0x4116c8, 0x100, 0x8774e0)
	/usr/lib/go-1.8/src/net/textproto/reader.go:55 +0x5f
net/textproto.(*Reader).ReadLine(0xc4939cc960, 0xc42547f100, 0x72, 0x8000000000000000, 0x0)
	/usr/lib/go-1.8/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc429144180, 0x0, 0xc42547f100, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/http/request.go:918 +0xa5
net/http.(*conn).readRequest(0xc476946000, 0xa64e40, 0xc4f3cdf740, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/http/server.go:934 +0x213
net/http.(*conn).serve(0xc476946000, 0xa64e40, 0xc4f3cdf740)
	/usr/lib/go-1.8/src/net/http/server.go:1763 +0x49a
created by net/http.(*Server).Serve
	/usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce

goroutine 908016 [IO wait]:
net.runtime_pollWait(0x7f660f2b7d60, 0x72, 0x146)
	/usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4254980d8, 0x72, 0xa61380, 0xa5d638)
	/usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4254980d8, 0xc427239000, 0x1000)
	/usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc425498070, 0xc427239000, 0x1000, 0x1000, 0x0, 0xa61380, 0xa5d638)
	/usr/lib/go-1.8/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42bcde4e0, 0xc427239000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/net.go:181 +0x70
net/http.(*connReader).Read(0xc42aa2dc00, 0xc427239000, 0x1000, 0x1000, 0x0, 0xa5f200, 0xc4200180e0)
	/usr/lib/go-1.8/src/net/http/server.go:754 +0x140
bufio.(*Reader).fill(0xc429144360)
	/usr/lib/go-1.8/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadSlice(0xc429144360, 0xa, 0xc, 0xb, 0xc4200359f8, 0x410966, 0x7f660f3d8e40)
	/usr/lib/go-1.8/src/bufio/bufio.go:338 +0xbb
bufio.(*Reader).ReadLine(0xc429144360, 0xc42006ab00, 0x100, 0xf8, 0x8774e0, 0xc42c541001, 0x17f660f3d4000)
	/usr/lib/go-1.8/src/bufio/bufio.go:367 +0x37
net/textproto.(*Reader).readLineSlice(0xc429a06090, 0xc420035ac8, 0xc420035ac8, 0x4116c8, 0x100, 0x8774e0)
	/usr/lib/go-1.8/src/net/textproto/reader.go:55 +0x5f
net/textproto.(*Reader).ReadLine(0xc429a06090, 0xc42006ab00, 0x72, 0x8000000000000000, 0x0)
	/usr/lib/go-1.8/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc429144360, 0x0, 0xc42006ab00, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/http/request.go:918 +0xa5
net/http.(*conn).readRequest(0xc4200d0640, 0xa64e40, 0xc42aa2dbc0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/http/server.go:934 +0x213
net/http.(*conn).serve(0xc4200d0640, 0xa64e40, 0xc42aa2dbc0)
	/usr/lib/go-1.8/src/net/http/server.go:1763 +0x49a
created by net/http.(*Server).Serve
	/usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce

goroutine 900585 [sleep]:
time.Sleep(0x989680)
	/usr/lib/go-1.8/src/runtime/time.go:59 +0xf9
github.com/dgraph-io/badger.(*DB).writeRequests(0xc420114600, 0xc42a569b80, 0x7, 0xa, 0xffff303735343131, 0x836d20)
	/home/mrjn/go/src/github.com/dgraph-io/badger/db.go:573 +0x25f
github.com/dgraph-io/badger.(*DB).doWrites.func1(0xc42a569b80, 0x7, 0xa)
	/home/mrjn/go/src/github.com/dgraph-io/badger/db.go:617 +0x55
created by github.com/dgraph-io/badger.(*DB).doWrites
	/home/mrjn/go/src/github.com/dgraph-io/badger/db.go:666 +0x3e5

goroutine 908219 [IO wait]:
net.runtime_pollWait(0x7f660f2b7ee0, 0x72, 0xd)
	/usr/lib/go-1.8/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc451c6a068, 0x72, 0xa61380, 0xa5d638)
	/usr/lib/go-1.8/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc451c6a068, 0xc42bc6aad1, 0x1)
	/usr/lib/go-1.8/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc451c6a000, 0xc42bc6aad1, 0x1, 0x1, 0x0, 0xa61380, 0xa5d638)
	/usr/lib/go-1.8/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e0d8, 0xc42bc6aad1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/net/net.go:181 +0x70
net/http.(*connReader).backgroundRead(0xc42bc6aac0)
	/usr/lib/go-1.8/src/net/http/server.go:656 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/go-1.8/src/net/http/server.go:652 +0xdf
```

**Comment by manishrjain** [comment]
Also, this log was being constantly updated, which is how I know it's the sleep statement and the condition around that sleep causing the stall.

```
03:14:23.783586 | . 10101 | ... Making room for writes
-- | -- | --
03:14:23.793683 | . 10097 | ... Making room for writes
03:14:23.803789 | . 10106 | ... Making room for writes
03:14:23.813890 | . 10100 | ... Making room for writes
03:14:23.823985 | . 10096 | ... Making room for writes
03:14:23.834095 | . 10109 | ... Making room for writes
03:14:23.844175 | . 10080 | ... Making room for writes
03:14:23.854270 | . 10096 | ... Making room for writes
03:14:23.864365 | . 10094 | ... Making room for writes


```

**Comment by janardhan1993** [comment]
@funny-falcon, can you increase the ulimit and try once. Set it to high number

**Comment by manishrjain** [comment]
Commit https://github.com/dgraph-io/badger/commit/1000ac56402cbc24ea02169f07d26f3bfd59a1ff should fix this issue.
