### ISSUE TITLE
Seeing panics on write

### ISSUE THREAD

**Issue by notbdu** [dgraph-io/badger#419]
We're seeing panics on writes. I'm posting the stack trace here for reference. Unfortunately, we don't have a repro for this specific bug. I can try to repro once our schedule clears up but that won't be in the immediate future.

We are running badger inside of `alpine:3.5` docker container on top of ubuntu 16.04.
```
panic: send on closed channel

goroutine 412 [running]:
github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger.(*DB).sendToWriteCh(0xc42036a600, 0xc420bed2b0, 0x2, 0x2, 0xc420293bb8, 0x10, 0x89

        /go/src/github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger/db.go:589 +0x168
github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger.(*DB).batchSet(0xc42036a600, 0xc420bed2b0, 0x2, 0x2, 0x4, 0x8)
        /go/src/github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger/db.go:659 +0x4d
github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger.(*Txn).Commit(0xc420be3440, 0x0, 0x0, 0x0)
        /go/src/github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger/transaction.go:500 +0x847
github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger.(*DB).Update(0xc42036a600, 0xc420293d70, 0x0, 0x0)
        /go/src/github.com/capsule8/reactive8/vendor/github.com/dgraph-io/badger/transaction.go:568 +0xd3
```

**Comment by manishrjain** [comment]
This happens if you do writes after closing the database.

**Comment by notbdu** [comment]
Thanks @manishrjain!

**Comment by notbdu** [comment]
Not a big deal, but shouldn't badger return an error in this case?

**Comment by manishrjain** [comment]
That'd be more elegant, yes. Feel free to file an issue.

**Comment by notbdu** [comment]
Will do! 👍
