### ISSUE TITLE
Using merge with existing database

### ISSUE THREAD

**Issue by LeonidShamis** [dgraph-io/badger#449]
Hello,

I have just started exploring Badger and tried using "merge" as explained in the projects description - https://github.com/dgraph-io/badger#merge-operations

The program works fine when creating a new database, but then it fails when running with the same (existing) database again.

I have even tried wrapping the code that uses merge in db.Update(...) function as shown in the project description - https://github.com/dgraph-io/badger#using-keyvalue-pairs - but the result was the same.

Here is a link to the GitHub repository with my code and the program output:

https://github.com/LeonidShamis/badger

```
leonid@ubuntu:~/go/src$ git clone https://github.com/LeonidShamis/badger.git
Cloning into 'badger'...
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 1), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (10/10), done.
Checking connectivity... done.
leonid@ubuntu:~/go/src$ cd badger
```
Next step:
- The database will be stored in /tmp/badger and the directory does not exist yet
- The program runs as expected
- The database is created

```
leonid@ubuntu:~/go/src/badger$ ls -l /tmp/badger
ls: cannot access '/tmp/badger': No such file or directory
leonid@ubuntu:~/go/src/badger$ go run use-merge.go
Before using merge... Check the current value, if exists...
Try using merge...
Result value:  6
leonid@ubuntu:~/go/src/badger$ ls -l /tmp/badger
total 12
-rw-rw-r-- 1 leonid leonid 1045 Apr  4 18:31 000000.vlog
-rw-rw-r-- 1 leonid leonid  428 Apr  4 18:31 000002.sst
-rw-rw-r-- 1 leonid leonid   48 Apr  4 18:31 MANIFEST
```
Next step:
- The database now exists
- The program is executed again
- This time we get failure

```
leonid@ubuntu:~/go/src/badger$ go run use-merge.go
Before using merge... Check the current value, if exists...
Value for the key merge:
Try using merge...
panic: runtime error: index out of range

goroutine 111 [running]:
encoding/binary.binary.bigEndian.Uint64(...)
        /usr/local/go/src/encoding/binary/binary.go:124
main.bytesToUint64(...)
        /home/leonid/go/src/badger/use-merge.go:17
main.add(0xc420014778, 0x8, 0x8, 0x0, 0x0, 0x0, 0xc420014778, 0x8, 0x8)
        /home/leonid/go/src/badger/use-merge.go:21 +0x82
github.com/dgraph-io/badger.(*MergeOperator).iterateAndMerge(0xc4256020f0, 0xc4200b0360, 0x4122b8, 0x30, 0x7b9bc0, 0xc420031e00, 0x42a249, 0xc400000008)
        /home/leonid/go/src/github.com/dgraph-io/badger/db.go:1264 +0x1e1
github.com/dgraph-io/badger.(*MergeOperator).compact.func1(0xc4200b0360, 0x7f0f90, 0xc4200b0360)
        /home/leonid/go/src/github.com/dgraph-io/badger/db.go:1282 +0x46
github.com/dgraph-io/badger.(*DB).Update(0xc42014e000, 0xc420031e98, 0x0, 0x0)
        /home/leonid/go/src/github.com/dgraph-io/badger/transaction.go:544 +0x111
github.com/dgraph-io/badger.(*MergeOperator).compact(0xc4256020f0, 0x0, 0x0)
        /home/leonid/go/src/github.com/dgraph-io/badger/db.go:1277 +0xa3
github.com/dgraph-io/badger.(*MergeOperator).runCompactions(0xc4256020f0, 0xbebc200)
        /home/leonid/go/src/github.com/dgraph-io/badger/db.go:1314 +0x171
created by github.com/dgraph-io/badger.(*DB).GetMergeOperator
        /home/leonid/go/src/github.com/dgraph-io/badger/db.go:1236 +0xd7
exit status 2
leonid@ubuntu:~/go/src/badger$
```

Thank you.

**Comment by manishrjain** [comment]
You need this to allow for `existing` to be a byte slice of zero length.

```
func bytesToUint64(b []byte) uint64 {
	if len(b) == 0 {
		return 0
	}

	return binary.BigEndian.Uint64(b)
}
```

**Comment by LeonidShamis** [comment]
Thank you very much, I've confirmed that your solution works properly:

```
leonid@ubuntu:~/go/src/badger$ go run use-merge.go
Before using merge... Check the current value, if exists...
Try using merge...
Result value:  6
leonid@ubuntu:~/go/src/badger$ go run use-merge.go
Before using merge... Check the current value, if exists...
Value for the key merge:
Try using merge...
Result value:  12
leonid@ubuntu:~/go/src/badger$
```
