### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by C-ollins** [dgraph-io/badger#553]
I got this error while running a get. It runs normally but randomly fails when I run gets from different transactions concurrently. It doesn’t fail immediately because I get results but I believe it happens when the garbage collector kicks in.

EDIT: I disabled garbage collector and error still came in.
```
08-17 17:40:48.660 5306-0/com.dcrandroid E/Go: panic: runtime error: invalid memory address or nil pointer dereference
    	panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8821b0c3]
    goroutine 18 [running, locked to thread]:
    github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/skl.(*Arena).reset(0x0)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/skl/arena.go:58 +0x13
    github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/skl.(*Skiplist).DecrRef(0x5f43e020)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/skl/skl.go:96 +0x3f
    github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger.(*DB).getMemTables.func1()
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/db.go:485 +0x30
    panic(0x88712ac0, 0x88a556c0)
    	/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x1f1
    github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/skl.(*Arena).getNode(...)
08-17 17:40:48.661 5306-0/com.dcrandroid E/Go: 	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/skl/arena.go:113
    github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/skl.(*Skiplist).getNext(0x5f43e020, 0x5f844008, 0x9, 0x0)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/skl/skl.go:176 +0x44
    github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/skl.(*Skiplist).findNear(0x5f43e020, 0x2d95820, 0xe, 0xe, 0x87df0100, 0x5f468010, 0x0)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/skl/skl.go:190 +0x4b
    github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/skl.(*Skiplist).Get(0x5f43e020, 0x2d95820, 0xe, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/skl/skl.go:376 +0x49
    github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger.(*DB).get(0x5f468000, 0x2d95820, 0xe, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/db.go:504 +0xfb
    github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger.(*Txn).Get(0x42ea540, 0x88a6dfec, 0x6, 0x6, 0x62a47e30, 0x87da6f19, 0x3ff)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/dgraph-io/badger/transaction.go:409 +0xde
    github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet/internal/walletdb/badgerdb.(*transaction).ReadWriteBucket(0x51b6ec0, 0x88a6dfec, 0x6, 0x6, 0x5f514000, 0x8a300000)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet/internal/walletdb/badgerdb/db.go:56 +0x39
    github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet/internal/walletdb/badgerdb.(*transaction).ReadBucket(0x51b6ec0, 0x88a6dfec, 0x6, 0x6, 0x87da7b46, 0x20)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet/internal/walletdb/badgerdb/db.go:52 +0x33
    github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet.(*Wallet).MainChainTip.func1(0x88793a30, 0x51b6ec0, 0x88793a30, 0x51b6ec0)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet/wallet.go:497 +0x57
    github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet/internal/walletdb.View(0x88794d00, 0x5f4640b8, 0x62a47f04, 0x0, 0x0)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet/internal/walletdb/interface.go:210 +0x9d
    github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet.(*Wallet).MainChainTip(0x5f440400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet/wallet.go:496 +0x62
    github.com/raedahgroup/mobilewallet.(*LibWallet).GetBestBlock(0x5f4127c0, 0x887828e0)
08-17 17:40:48.662 5306-0/com.dcrandroid E/Go: 	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/mobilewallet.go:862 +0x1e
    main.proxymobilewallet_LibWallet_GetBestBlock(0xffffffe7, 0x87dc1291)
    	/var/folders/_z/21zf85t530b1wz5mzpmrqrkc0000gp/T/gomobile-work-482603031/src/gobind/go_mobilewalletmain.go:817 +0x46
    main._cgoexpwrap_9af00da4bc3a_proxymobilewallet_LibWallet_GetBestBlock(0xffffffe7, 0x1ff6)
    	_cgo_gotypes.go:1665 +0x1b
    
```

**Comment by C-ollins** [comment]
I get this if I try to open the database after the crash.

"file does not exist for table 2"

```
panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x88351439]
    goroutine 22 [running]:
    github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet/internal/walletdb/badgerdb.openDB.func1(0x0)
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet/internal/walletdb/badgerdb/db.go:555 +0x79
    created by github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet/internal/walletdb/badgerdb.openDB
    	/Users/collins/go/src/github.com/raedahgroup/mobilewallet/vendor/github.com/decred/dcrwallet/wallet/internal/walletdb/badgerdb/db.go:551 +0x13f
```

**Comment by manishrjain** [comment]
Can you share your code? In general, ensure that you're not closing the DB and then doing gets.

**Comment by C-ollins** [comment]
I'm starting to think that this is happening because I tweaked the db options. Here's what I'm currently using.
```
ValueLogLoadingMode = options.FileIO
TableLoadingMode = options.MemoryMap
ValueLogFileSize = 209715200
MaxTableSize = 40000000
LevelOneSize = 209715200
NumMemtables = 1
NumCompactors = 1
NumLevelZeroTables = 1
NumLevelZeroTablesStall = 2
```
Crash is happening at
```
func (s *Arena) reset() {
	fmt.Println("S.n size: ", s.size())
	atomic.StoreUint32(&s.n, 0)
}
```

`fmt.Println("S.n size: ", s.size())` returned `2306514` which shows &s.n isn't nil. So where could the nil pointer dereference be coming from?

**Comment by C-ollins** [comment]
The bug happened to be coming from closing an iterator twice. Not a issue from badger.
