### ISSUE TITLE
Calling iterator.Close() twice causes panic on next commit.

### ISSUE THREAD

**Issue by lsmith130** [dgraph-io/badger#554]
I read in the docs that it's ok for `txn.Close()` to be called multiple times, so I assumed this applied to iterators as well. I'm doing a database migration, so I'm using an iterator in a writable transaction. Since commit requires the iterator to be closed, and I'm using manual transactions, I did a `defer iterator.Close()` to cover error cases, and another direct `iterator.Close()` just before committing. This seemed to work fine, until I ran a second commit later in an unrelated part of the program which gave the following panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8393bd]

goroutine 54 [running]:
github.com/dgraph-io/badger/skl.(*Arena).size(...)
	/Users/l/Code/src/github.com/dgraph-io/badger/skl/arena.go:54
github.com/dgraph-io/badger/skl.(*Skiplist).MemSize(...)
	/Users/l/Code/src/github.com/dgraph-io/badger/skl/skl.go:400
github.com/dgraph-io/badger.(*DB).ensureRoomForWrite(0xc00005d180, 0x0, 0x0)
	/Users/l/Code/src/github.com/dgraph-io/badger/db.go:750 +0x8d
github.com/dgraph-io/badger.(*DB).writeRequests(0xc00005d180, 0xc00001e0a0, 0x1, 0xa, 0x0, 0x0)
	/Users/l/Code/src/github.com/dgraph-io/badger/db.go:602 +0x1ad
github.com/dgraph-io/badger.(*DB).doWrites.func1(0xc00001e0a0, 0x1, 0xa)
	/Users/l/Code/src/github.com/dgraph-io/badger/db.go:657 +0x55
created by github.com/dgraph-io/badger.(*DB).doWrites
	/Users/l/Code/src/github.com/dgraph-io/badger/db.go:706 +0x30e
```

Now that I've figured out that it's the double `iterator.Close()` causing the issue, it's fairly easy to work around, but I thought I'd open an issue to help others who might run into this.

**Comment by lsmith130** [comment]
On second thought, the issue probably isn't that I'm calling `iterator.Close()` twice, but that the deferred call is running after the commit, so the txn is already discarded.

**Comment by manishrjain** [comment]
Maybe you can send an update to the README to warn others about this.
