### ISSUE TITLE
Bank test failing in Badger

### ISSUE THREAD

**Issue by manishrjain** [dgraph-io/badger#574]
The new bank test I wrote for Badger is able to see transaction violations.

```
$ badger test --dir=banktest -d=10m

...

2018/09/20 17:31:19 Total: 251994. Success: 251197. Errors: 797 Reads: 551.
2018/09/20 17:31:20 Total: 252603. Success: 251797. Errors: 806 Reads: 552.
panic: Balance did NOT match up. Expected: 100000000. Received: 100000005

goroutine 1000584 [running]:
github.com/dgraph-io/badger/badger/cmd.totalMoney.func1(0xc42e3d4c60, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/badger/cmd/bank.go:145 +0x341
github.com/dgraph-io/badger.(*DB).View(0xc4201a4000, 0xc42c508f10, 0x0, 0x0)
	/home/mrjn/go/src/github.com/dgraph-io/badger/transaction.go:590 +0x92
github.com/dgraph-io/badger/badger/cmd.totalMoney(0xc4201a4000, 0x6134a34f78, 0xb55420)
	/home/mrjn/go/src/github.com/dgraph-io/badger/badger/cmd/bank.go:130 +0x51
github.com/dgraph-io/badger/badger/cmd.runTest.func4(0xc42f61e6a0, 0xbee12d04fa130e92, 0x8cbc4da988, 0xb55420, 0xc4201a4000, 0xc42dfdfb60)
	/home/mrjn/go/src/github.com/dgraph-io/badger/badger/cmd/bank.go:256 +0x139
created by github.com/dgraph-io/badger/badger/cmd.runTest
	/home/mrjn/go/src/github.com/dgraph-io/badger/badger/cmd/bank.go:242 +0x7a1
```

Badger is seeing an ACID violation during concurrent transactions. Needs investigation.

**Comment by manishrjain** [comment]
Phew! That was mind-boggling.
