### ISSUE TITLE
Nil pointer exception running on ARM chip (Raspberry Pi)

### ISSUE THREAD

**Issue by romansemko** [dgraph-io/badger#610]
Golang version: 1.11
Badger: latest from master

Minimal example from README, adding `db.View` in the end: 
```golang
package main

import (
        "log"

        "github.com/dgraph-io/badger/options"
        "github.com/dgraph-io/badger"
)

func main() {
  // Open the Badger database located in the /tmp/badger directory.
  // It will be created if it doesn't exist.
  opts := badger.DefaultOptions
  opts.Dir = "/tmp/badger"
  opts.ValueDir = "/tmp/badger"
  opts.ValueLogLoadingMode = options.FileIO 
  opts.TableLoadingMode = options.FileIO
  db, err := badger.Open(opts)
  if err != nil {
          log.Fatal(err)
  }
  defer db.Close()
  
  // Fails here:
  db.View(func(txn *badger.Txn) error {
    return nil
  })
}
```

Result when running:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x125b0]

goroutine 1 [running]:
runtime/internal/atomic.goStore64(0x8a42e4, 0x0, 0x0)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:137 +0x1c
github.com/dgraph-io/badger/y.(*WaterMark).Begin(0x8a42d0, 0x0, 0x0)
        /home/pi/go/src/github.com/dgraph-io/badger/y/watermark.go:74 +0x34
github.com/dgraph-io/badger.(*oracle).readTs(0x8a4280, 0x5c382d0, 0x5c26030)
        /home/pi/go/src/github.com/dgraph-io/badger/txn.go:102 +0x68
github.com/dgraph-io/badger.(*DB).newTransaction(0x8da200, 0x0, 0xf4240)
        /home/pi/go/src/github.com/dgraph-io/badger/txn.go:718 +0xb4
github.com/dgraph-io/badger.(*DB).NewTransaction(0x8da200, 0x2f4500, 0x5c2604c)
        /home/pi/go/src/github.com/dgraph-io/badger/txn.go:686 +0x2c
github.com/dgraph-io/badger.(*DB).View(0x8da200, 0x3aa9fc, 0x0, 0x0)
        /home/pi/go/src/github.com/dgraph-io/badger/txn.go:731 +0xc0
main.main()
        /home/pi/nikita/test.go:25 +0xdc
```

on Mac it works just fine...

**Comment by Lesterpig** [comment]
I'm encountering the same issue on an armv7 device

**Comment by manishrjain** [comment]
Thanks for your PR to fix this, @Lesterpig .

**Comment by Lesterpig** [comment]
I hope this will be sufficient :smiley:

**Comment by romansemko** [comment]
Thank you!
