### ISSUE TITLE
panic when call update after close db

### ISSUE THREAD

**Issue by ysqi** [dgraph-io/badger#627]
panic: send on closed channel

```text
goroutine 23 [running]:
github.com/dgraph-io/badger.(*DB).sendToWriteCh(0xc4200a9500, 0xc4203001b0, 0x2, 0x2, 0x1, 0x8, 0x13)
	$GOPATH/src/github.com/dgraph-io/badger/db.go:651 +0x15f
github.com/dgraph-io/badger.(*Txn).commitAndSend(0xc420432200, 0x0, 0x0, 0x0)
	$GOPATH/src/github.com/dgraph-io/badger/txn.go:539 +0x485
github.com/dgraph-io/badger.(*Txn).Commit(0xc420432200, 0x0, 0x0)
	$GOPATH/src/github.com/dgraph-io/badger/txn.go:590 +0x78
github.com/dgraph-io/badger.(*DB).Update(0xc4200a9500, 0xc42015fa68, 0x0, 0x0)
	$GOPATH/src/github.com/dgraph-io/badger/txn.go:744 +0xbb
```

my code:
```go
err = w.db.Update(func(txn *badger.Txn) error {
  ...
}
...
defer db.Close()
test(t, db)  // stop
```

**Comment by manishrjain** [comment]
This indicates that you're calling update after closing the DB. So, the panic makes sense. See FAQ:

https://github.com/dgraph-io/badger#frequently-asked-questions
