### ISSUE TITLE
got oom in production environment (4c8g node)

### ISSUE THREAD

**Issue by zhiqiangxu** [dgraph-io/badger#632]
Using the latest master branch, got this:

```
badger2018/11/30 18:23:30 INFO: Replaying file id: 64 at offset: 68633703
badger2018/11/30 18:23:32 INFO: Replay took: 1.945791909s
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xa0a132, 0x16) 
        /usr/local/go/src/runtime/panic.go:616 +0x81 
runtime.sysMap(badger2018/11/30 18:24:21 INFO: Replaying file id: 64 at offset: 68633703
badger2018/11/30 18:24:23 INFO: Replay took: 1.990920916s
badger2018/11/30 18:25:06 INFO: Replaying file id: 64 at offset: 68633703
badger2018/11/30 18:25:09 INFO: Replay took: 2.092865072s
badger2018/11/30 18:25:56 INFO: Replaying file id: 64 at offset: 68633703
badger2018/11/30 18:25:58 INFO: Replay took: 1.982146705s
badger2018/11/30 18:26:48 INFO: Replaying file id: 64 at offset: 68633703
badger2018/11/30 18:26:50 INFO: Replay took: 2.150969863s
panic: send on closed channel

goroutine 508266 [running]:
qpush/vendor/github.com/dgraph-io/badger.(*DB).sendToWriteCh(0xc42018ea80, 0xc51d98ab40, 0x2, 0x2, 0x8, 0x8, 0x13) 
        /home/pipixia/new_compilebuild/tmp/COMPILE_SRC/qpush-data/src/qpush/vendor/github.com/dgraph-io/badger/db.go:652 +0x15f
qpush/vendor/github.com/dgraph-io/badger.(*Txn).commitAndSend(0xc4b85b7000, 0x0, 0x0, 0x0)
        /home/pipixia/new_compilebuild/tmp/COMPILE_SRC/qpush-data/src/qpush/vendor/github.com/dgraph-io/badger/txn.go:539 +0x485
qpush/vendor/github.com/dgraph-io/badger.(*Txn).Commit(0xc4b85b7000, 0x0, 0x0)
        /home/pipixia/new_compilebuild/tmp/COMPILE_SRC/qpush-data/src/qpush/vendor/github.com/dgraph-io/badger/txn.go:590 +0x78
qpush/vendor/github.com/dgraph-io/badger.(*DB).Update(0xc42018ea80, 0xc5125e6e10, 0x0, 0x0)
        /home/pipixia/new_compilebuild/tmp/COMPILE_SRC/qpush-data/src/qpush/vendor/github.com/dgraph-io/badger/txn.go:744 +0xbb
```

The total size of sst files is less than 2G:

````[work@k8s-d-245 ~]$ du -sh /data/badger/*.sst
67M	/data/badger/000323.sst
67M	/data/badger/000325.sst
67M	/data/badger/000327.sst
67M	/data/badger/000328.sst
67M	/data/badger/000329.sst
67M	/data/badger/000330.sst
62M	/data/badger/000331.sst
2.2M	/data/badger/000358.sst
67M	/data/badger/000368.sst
67M	/data/badger/000369.sst
67M	/data/badger/000371.sst
67M	/data/badger/000373.sst
67M	/data/badger/000374.sst
67M	/data/badger/000375.sst
67M	/data/badger/000376.sst
67M	/data/badger/000377.sst
67M	/data/badger/000378.sst
67M	/data/badger/000379.sst
67M	/data/badger/000380.sst
67M	/data/badger/000381.sst
67M	/data/badger/000382.sst
67M	/data/badger/000383.sst
44M	/data/badger/000384.sst
51M	/data/badger/000385.sst
62M	/data/badger/000386.sst
[work@k8s-d-245 ~]$ du -sh /data/badger/
43G	/data/badger/
[work@k8s-d-245 ~]$ free -h
              total        used        free      shared  buff/cache   available
Mem:           7.6G        3.5G        3.1G        724K        979M        3.8G
Swap:            0B          0B          0B

````

Is badger production ready yet?

**Comment by manishrjain** [comment]
I see this in your stack trace: "panic: send on closed channel"

See faqs.

**Comment by zhiqiangxu** [comment]
> I see this in your stack trace: "panic: send on closed channel"
> 
> See faqs. Badger is being used to serve hundreds of TBs of data. It is prod ready.

I have no problem with the panic, as I will `db.Close()` when signaled.

**Comment by manishrjain** [comment]
You can take a memory profile and see what's going on. Also, what are the options you are setting?

**Comment by zhiqiangxu** [comment]
> You can take a memory profile and see what's going on. Also, what are the options you are setting?

I'll provide memory profile if it happens again.

This is the options I'm using:

```opts := badger.DefaultOptions
opts.SyncWrites = false```

I ensure to call `db.Close()` before exit, so I think it's fine, because my first priority is latency, currently the latency is 10 millisecond for more than 10%  of random key read requests, is this normal?

**Comment by manishrjain** [comment]
Go is only using 3GB, as per the memory profiler.
