### ISSUE TITLE
Panic on Get

### ISSUE THREAD

**Issue by Stebalien** [dgraph-io/badger#735]
I'm seeing some panics when killing go-ipfs on startup. I'm _guessing_ this may have something to do with concurrently(?) closing the datastore. Is that not supported (we could add a read-write lock around everything)?

Let me know what else you need to debug this.

Badger commit 8115aed38f8f8cd248d832f51c27700efc25b201

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x122c2f7]

goroutine 1 [running]:
github.com/dgraph-io/badger/skl.(*Skiplist).IncrRef(...)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190226225317-8115aed38f8f/skl/skl.go:86
github.com/dgraph-io/badger.(*DB).getMemTables(0xc0003cc000, 0x0, 0x0, 0x0, 0x0)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190226225317-8115aed38f8f/db.go:453 +0xd7
github.com/dgraph-io/badger.(*DB).get(0xc0003cc000, 0xc000395f00, 0x13, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190226225317-8115aed38f8f/db.go:485 +0x66
github.com/dgraph-io/badger.(*Txn).Get(0xc009dfc080, 0xc0095cde10, 0xb, 0x10, 0xb, 0x10, 0xc0003af4b0)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190226225317-8115aed38f8f/txn.go:459 +0xe7
github.com/ipfs/go-ds-badger.(*txn).Get(0xc009551290, 0x16d02f6, 0xb, 0x17f887d3001354d0, 0xc0003af510, 0x9217df, 0xc0002b71d0, 0xc0003af530)
	/home/steb/projects/go/pkg/mod/github.com/ipfs/go-ds-badger@v0.0.2/datastore.go:239 +0x75
github.com/ipfs/go-ds-badger.(*Datastore).Get(0xc000132290, 0x16d02f6, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/steb/projects/go/pkg/mod/github.com/ipfs/go-ds-badger@v0.0.2/datastore.go:145 +0xe0
github.com/ipfs/go-ds-measure.(*measure).Get(0xc0000d8480, 0x16d02f6, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/steb/projects/go/pkg/mod/github.com/ipfs/go-ds-measure@v0.0.1/measure.go:149 +0xd4
github.com/ipfs/go-ds-measure.(*measure).Get(0xc0000d8900, 0x16d02f6, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/steb/projects/go/pkg/mod/github.com/ipfs/go-ds-measure@v0.0.1/measure.go:149 +0xd4
github.com/ipfs/go-ipfs/pin.LoadPinner(0x6802bc911400, 0xc0000d8900, 0x19cfd20, 0xc009551260, 0x19cfd20, 0xc009551280, 0x0, 0x0, 0x0, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/pin/pin.go:455 +0x94
github.com/ipfs/go-ipfs/core.setupNode(0x19c8540, 0xc000264840, 0xc00000c1e0, 0xc00933c2c0, 0xc0000c9140, 0xc000076100)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/builder.go:268 +0xa78
github.com/ipfs/go-ipfs/core.NewNode(0x19c8480, 0xc0000ca640, 0xc00933c2c0, 0x0, 0xc0000d7058, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/builder.go:159 +0x5a6
main.daemonFunc(0xc000392000, 0x19c8880, 0xc0000c8960, 0x199e860, 0xc0000c8900, 0x0, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/daemon.go:330 +0x5eb
github.com/ipfs/go-ipfs-cmds.(*executor).Execute(0xc0000c60c8, 0xc000392000, 0x19c8880, 0xc0000c8960, 0x199e860, 0xc0000c8900, 0xc0000c8960, 0x0)
	/home/steb/projects/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/executor.go:81 +0x15d
github.com/ipfs/go-ipfs-cmds/cli.Run(0x19c8480, 0xc0002aaa80, 0x2396b40, 0xc0000ba020, 0x2, 0x2, 0xc0000c6000, 0xc0000c6008, 0xc0000c6010, 0x1855280, ...)
	/home/steb/projects/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/cli/run.go:138 +0xa69
main.mainRet(0x0)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:179 +0x421
main.main()
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:85 +0x22
```

Badger commit 75e07ee98a40edd5eba538ca6325a63973444b5d

```
unexpected fault address 0x60ffa801a000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60ffa801a000 pc=0x121d38d]

goroutine 1 [running]:
runtime.throw(0x16c9b5a, 0x5)
	/usr/lib/go/src/runtime/panic.go:617 +0x72 fp=0xc0003daec8 sp=0xc0003dae98 pc=0x922a62
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:397 +0x401 fp=0xc0003daef8 sp=0xc0003daec8 pc=0x939121
encoding/binary.bigEndian.Uint16(...)
	/usr/lib/go/src/encoding/binary/binary.go:101
github.com/dgraph-io/badger/table.(*header).Decode(0xc0003daf34, 0x60ffa801a000, 0x245, 0x2c5, 0x90)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190307231736-75e07ee98a40/table/builder.go:56 +0x1d fp=0xc0003daf08 sp=0xc0003daef8 pc=0x121d38d
github.com/dgraph-io/badger/table.(*blockIterator).Next(0xc00012a480)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190307231736-75e07ee98a40/table/iterator.go:139 +0xea fp=0xc0003daf58 sp=0xc0003daf08 pc=0x121ef0a
github.com/dgraph-io/badger/table.(*blockIterator).Init(...)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190307231736-75e07ee98a40/table/iterator.go:54
github.com/dgraph-io/badger/table.(*blockIterator).SeekToFirst(...)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190307231736-75e07ee98a40/table/iterator.go:99
github.com/dgraph-io/badger/table.(*Iterator).next(0xc0093c9bc0)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190307231736-75e07ee98a40/table/iterator.go:343 +0x217 fp=0xc0003dafd0 sp=0xc0003daf58 pc=0x121fe87
github.com/dgraph-io/badger/table.(*Table).NewIterator(0xc009350000, 0x0, 0xc0003c2100)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190307231736-75e07ee98a40/table/iterator.go:209 +0x69 fp=0xc0003daff8 sp=0xc0003dafd0 pc=0x121f379
github.com/dgraph-io/badger.(*levelHandler).get(0xc0003f6060, 0xc0000d5ca0, 0x13, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190307231736-75e07ee98a40/level_handler.go:241 +0x21e fp=0xc0003db168 sp=0xc0003daff8 pc=0x1237dee
github.com/dgraph-io/badger.(*levelsController).get(0xc0002c5810, 0xc0000d5ca0, 0x13, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190307231736-75e07ee98a40/levels.go:906 +0xe3 fp=0xc0003db248 sp=0xc0003db168 pc=0x12407a3
github.com/dgraph-io/badger.(*DB).get(0xc0001cc300, 0xc0000d5ca0, 0x13, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190307231736-75e07ee98a40/db.go:514 +0x322 fp=0xc0003db378 sp=0xc0003db248 pc=0x122c782
github.com/dgraph-io/badger.(*Txn).Get(0xc00015f680, 0xc0000c58e0, 0xb, 0x10, 0xb, 0x10, 0xc0003db4b0)
	/home/steb/projects/go/pkg/mod/github.com/dgraph-io/badger@v1.5.5-0.20190307231736-75e07ee98a40/txn.go:459 +0xe7 fp=0xc0003db450 sp=0xc0003db378 pc=0x1249227
github.com/ipfs/go-ds-badger.(*txn).Get(0xc0000afc70, 0x16d16c4, 0xb, 0x67a0a43002c9170, 0xc0003db510, 0x9217df, 0xc0094ba9f0, 0xc0003db530)
	/home/steb/projects/go/src/github.com/ipfs/go-ds-badger/datastore.go:248 +0x75 fp=0xc0003db4c0 sp=0xc0003db450 pc=0x12601f5
github.com/ipfs/go-ds-badger.(*Datastore).Get(0xc000132280, 0x16d16c4, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/go-ds-badger/datastore.go:154 +0xe0 fp=0xc0003db520 sp=0xc0003db4c0 pc=0x125f4c0
github.com/ipfs/go-ds-measure.(*measure).Get(0xc0001a4000, 0x16d16c4, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/steb/projects/go/pkg/mod/github.com/ipfs/go-ds-measure@v0.0.1/measure.go:149 +0xd4 fp=0xc0003db570 sp=0xc0003db520 pc=0x11a4294
github.com/ipfs/go-ds-measure.(*measure).Get(0xc0001a4240, 0x16d16c4, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/steb/projects/go/pkg/mod/github.com/ipfs/go-ds-measure@v0.0.1/measure.go:149 +0xd4 fp=0xc0003db5c0 sp=0xc0003db570 pc=0x11a4294
github.com/ipfs/go-ipfs/pin.LoadPinner(0x60ffa80e4220, 0xc0001a4240, 0x19d14a0, 0xc0000afc40, 0x19d14a0, 0xc0000afc60, 0x0, 0x0, 0x0, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/pin/pin.go:455 +0x94 fp=0xc0003db708 sp=0xc0003db5c0 pc=0xe35f14
github.com/ipfs/go-ipfs/core.setupNode(0x19c9c60, 0xc000280960, 0xc00000c1e0, 0xc0000ca900, 0xc0000c9680, 0xc0000aec30)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/builder.go:268 +0xa78 fp=0xc0003db928 sp=0xc0003db708 pc=0x11787b8
github.com/ipfs/go-ipfs/core.NewNode(0x19c9ba0, 0xc0002c6a40, 0xc0000ca900, 0x0, 0xc0001f75e8, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/core/builder.go:159 +0x5a6 fp=0xc0003dba18 sp=0xc0003db928 pc=0x1177a56
main.daemonFunc(0xc0002c56c0, 0x19c9fa0, 0xc00012d8c0, 0x199ff80, 0xc00012d860, 0x0, 0x0)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/daemon.go:330 +0x5eb fp=0xc0003dbc68 sp=0xc0003dba18 pc=0x13e514b
github.com/ipfs/go-ipfs-cmds.(*executor).Execute(0xc000162548, 0xc0002c56c0, 0x19c9fa0, 0xc00012d8c0, 0x199ff80, 0xc00012d860, 0xc00012d8c0, 0x0)
	/home/steb/projects/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/executor.go:81 +0x15d fp=0xc0003dbd38 sp=0xc0003dbc68 pc=0x12db0dd
github.com/ipfs/go-ipfs-cmds/cli.Run(0x19c9ba0, 0xc0002c6a00, 0x2398b40, 0xc0000b8020, 0x2, 0x2, 0xc0000c6000, 0xc0000c6008, 0xc0000c6010, 0x1856710, ...)
	/home/steb/projects/go/pkg/mod/github.com/ipfs/go-ipfs-cmds@v0.0.1/cli/run.go:138 +0xa69 fp=0xc0003dbec8 sp=0xc0003dbd38 pc=0x13e32a9
main.mainRet(0x0)
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:179 +0x421 fp=0xc0003dbf80 sp=0xc0003dbec8 pc=0x13ebfd1
main.main()
	/home/steb/projects/go/src/github.com/ipfs/go-ipfs/cmd/ipfs/main.go:85 +0x22 fp=0xc0003dbf98 sp=0xc0003dbf80 pc=0x13ebb92
runtime.main()
	/usr/lib/go/src/runtime/proc.go:200 +0x20c fp=0xc0003dbfe0 sp=0xc0003dbf98 pc=0x92510c
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0003dbfe8 sp=0xc0003dbfe0 pc=0x952d81
```

**Comment by Stebalien** [comment]
Nevermind. Apparently this is https://github.com/dgraph-io/badger/pull/437.

**Comment by Stebalien** [comment]
(sorry, thought I had closed that)
