### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/badger#781]
not sure if it is already tracked. got it right now on data load on 1.0.14-rc1
```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: Unclosed iterator at time of Txn.Discard.
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xe81578]

goroutine 81461552 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Txn).Discard(0xc041ce9c00)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/txn.go:490 +0xde
panic(0x13a03a0, 0x20201c0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).deleteLogFile(0xc0005da458, 0x0, 0x1e, 0x20feae0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:558 +0x38
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).decrIteratorCount(0xc0005da458, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:550 +0x25b
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Iterator).Close(0xc03fcc21e0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:484 +0xb7
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).produceKVs.func1(0x0, 0x0, 0x0, 0xc032c83ee0, 0x1b, 0x20, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:185 +0x6ed
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).produceKVs(0xc0652aed20, 0x1678aa0, 0xc0000c0010, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:195 +0x28c
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).Orchestrate.func1(0xc042eec440, 0xc0652aed20, 0x1678aa0, 0xc0000c0010, 0xc00198d740)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:298 +0x69
created by github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).Orchestrate
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:295 +0x175
```

logs are here: https://drive.google.com/file/d/1aGPt9msqDC-iFAA2PzZWTpr4l3XN4_c4/view?usp=sharing

**Comment by simsolTech** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1420111]

goroutine 1 [running]:
simbaaz/uploads.PlacesUpload(0xc0000f9ce0, 0x0, 0x0)
        /Users/deepaktr/MyDocuments/graphql/simbaaz/uploads/places.go:77 +0x891
main.uploadMasters(0xc0000f9ce0)
        /Users/deepaktr/MyDocuments/graphql/simbaaz/main.go:69 +0x2f
main.main()
        /Users/deepaktr/MyDocuments/graphql/simbaaz/main.go:37 +0x29c
exit status 2

**Comment by jarifibrahim** [comment]
@simsolTech I don't see badger in your stack trace. Can you show me the code? I don't think the panic is from badger.
