### ISSUE TITLE
Badger fatal panic

### ISSUE THREAD

**Issue by zerjioang** [dgraph-io/badger#785]
I do have badger as DB in my project and when serving an endpoint over REST I encounter with this panic, when I call PutKeyValue. This method is defined as follows and it is called each time http client makes a request to the server. On each request, the panic is thrown

```go
func (db *Db) PutKeyValue(key []byte, value []byte) error {
	err := db.instance.Update(func(txn *badger.Txn) error {
		err := txn.Set(key, value)
		return err
	})
	return err
}
```

And the error thrown is:

```bash
echo: http: panic serving 127.0.0.1:56570: send on closed channel
goroutine 27 [running]:
net/http.(*conn).serve.func1(0xc8d9e0)
	/usr/local/go/src/net/http/server.go:1769 +0xf0
panic(0x5339d8, 0x67e9c0)
	/usr/local/go/src/runtime/panic.go:522 +0x1a0
go/src/path/to/my/project/vendor/github.com/dgraph-io/badger.(*DB).sendToWriteCh(0xcd0700, 0x1080c20, 0x2, 0x2, 0x1, 0x8, 0x13)
	/go/src/path/to/my/project/vendor/github.com/dgraph-io/badger/db.go:646 +0x1e0
go/src/path/to/my/project/vendor/github.com/dgraph-io/badger.(*Txn).Commit(0xc8daa0, 0x0, 0x0, 0x0)
	/go/src/path/to/my/project/vendor/github.com/dgraph-io/badger/transaction.go:511 +0x404
go/src/path/to/my/project/vendor/github.com/dgraph-io/badger.(*DB).Update(0xcd0700, 0xc3da6c, 0x0, 0x0)
	/go/src/path/to/my/project/vendor/github.com/dgraph-io/badger/transaction.go:603 +0xb0
go/src/path/to/my/project/core/db.(*Db).PutKeyValue(0xf6ce78, 0xe47f30, 0x5, 0xa, 0x676aee0, 0xda, 0xe0, 0xe47f00, 0x8)
	/go/src/path/to/my/project/core/db/badger.go:86 +0x6c
go/src/path/to/my/project/core/modules/cyber.Analytics.func1(0x68d400, 0x10cd180, 0x58ff57, 0xa)
	/go/src/path/to/my/project/cyber/analytics.go:48 +0x4b8
```

**Comment by ashish-goswami** [comment]
@zerjioang what is the version of Badger you are using?
Normally above panic happens, if **Update** is called on already closed DB. Hence can you also verify, if you are closing DB anywhere accidentally?

**Comment by zerjioang** [comment]
@ashish-goswami according to mi Gopkg.lock file, Im using
```bash
revision = "99233d725dbdd26d156c61b2f42ae1671b794656"
version = "v1.5.4"
```

And yes, I just call `badger.Open()` without closing connection anywhere.

**Comment by ashish-goswami** [comment]
@zerjioang tried to reproduce issue using below code. It is working fine. Can you check if I am missing something?
```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/dgraph-io/badger"
)

var DB *badger.DB

func initDB() {
	ops := badger.DefaultOptions
	ops.Dir = "/tmp/badger"
	ops.ValueDir = "/tmp/badger"

	db, err := badger.Open(ops)
	if err != nil {
		log.Fatalln(err)
	}

	DB = db
}

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		key, value := r.URL.Query().Get("key"), r.URL.Query().Get("val")
		err := DB.Update(func(t *badger.Txn) error {
			return t.Set([]byte(key), []byte(value))
		})

		if err != nil {
			fmt.Fprintf(w, "err: %s", err)
		} else {
			fmt.Println("stored key: ", key, " value ", value)
		}
	})

	initDB()

	http.ListenAndServe(":32000", nil)
}
```

**Comment by zerjioang** [comment]
Its still failing with same error. May it be a filesystem related issue? or even architecture related? Im having this error when running on arm

**Comment by ashish-goswami** [comment]
@zerjioang It might be. Please tell us all the information related to platform(OS and hardware with versions), you are using for running Badger. Also can you try reproducing it with latest master?

**Comment by zerjioang** [comment]
here are the details
```bash
$ lscpu

Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           Marvell
Model:               2
Model name:          PJ4B-MP
Stepping:            0x2
CPU max MHz:         1333.0000
CPU min MHz:         666.5000
BogoMIPS:            50.00
Flags:               half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae
```

```bash
    description: ARMv7 Processor rev 2 (v7l)
    product: Scaleway - C1 Computing
    width: 32 bits
    capabilities: smp
  *-core
       description: Motherboard
       physical id: 0
     *-cpu:0
          description: CPU
          product: cpu
          physical id: 0
          bus info: cpu@0
          size: 1333MHz
          capacity: 1333MHz
          capabilities: half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae cpufreq
     *-cpu:1
          description: CPU
          product: cpu
          physical id: 1
          bus info: cpu@1
          size: 1333MHz
          capacity: 1333MHz
          capabilities: half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae cpufreq
     *-cpu:2
          description: CPU
          product: cpu
          physical id: 2
          bus info: cpu@2
          size: 1333MHz
          capacity: 1333MHz
          capabilities: half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae cpufreq
     *-cpu:3
          description: CPU
          product: cpu
          physical id: 3
          bus info: cpu@3
          size: 1333MHz
          capacity: 1333MHz
          capabilities: half thumb fastmult vfp edsp thumbee vfpv3 tls idiva idivt vfpd32 lpae cpufreq
     *-memory
          description: System memory
          physical id: 4
          size: 2019MiB
  *-network:0
       description: Ethernet interface
       physical id: 1
       logical name: eth0
       size: 1Gbit/s
       capacity: 1Gbit/s
       capabilities: ethernet physical tp mii 1000bt 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=mvneta driverversion=1.0 duplex=full ip=10.1.43.66 link=yes multicast=yes port=MII speed=1Gbit/s
  *-network:1
       description: Ethernet interface
       physical id: 2
       logical name: veth1474fdb
       size: 10Gbit/s
       capabilities: ethernet physical
       configuration: autonegotiation=off broadcast=yes driver=veth driverversion=1.0 duplex=full link=yes multicast=yes port=twisted pair speed=10Gbit/s
  *-network:2
       description: Ethernet interface
       physical id: 3
       logical name: docker0
       capabilities: ethernet physical
       configuration: broadcast=yes driver=bridge driverversion=2.3 firmware=N/A ip=172.17.0.1 link=yes multicast=yes
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.
```

**Comment by ashish-goswami** [comment]
@zerjioang Is it still happening for you? If yes, please tell a way for us to reproduce it?

**Comment by zerjioang** [comment]
I did an update using latest version available, an no errors so far. So we can close the issue
