### ISSUE TITLE
runtime error: invalid memory address or nil pointer deference

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/badger#93]
This happens regularly on Travis macOS when running tests for Dgraph. Have to check how to reproduce it locally.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x43a9a7a]
goroutine 30675 [running]:
github.com/dgraph-io/badger/skl.(*Skiplist).IncrRef(0x0)
	/Users/travis/gopath/src/github.com/dgraph-io/badger/skl/skl.go:95 +0xa
github.com/dgraph-io/badger.(*KV).getMemTables(0xc42011c600, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/dgraph-io/badger/kv.go:316 +0x10c
github.com/dgraph-io/badger.(*KV).get(0xc42011c600, 0xc4604419d0, 0x10, 0x10, 0x0, 0x0, 0x0, 0x4a00, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/dgraph-io/badger/kv.go:359 +0x7d
github.com/dgraph-io/badger.(*KV).Get(0xc42011c600, 0xc4604419d0, 0x10, 0x10, 0xc474544b80, 0xa71eb65795429c54, 0x402c316)
	/Users/travis/gopath/src/github.com/dgraph-io/badger/kv.go:374 +0x67
github.com/dgraph-io/dgraph/posting.getNew(0xc4604419d0, 0x10, 0x10, 0xc42011c600, 0x0)
	/Users/travis/gopath/src/github.com/dgraph-io/dgraph/posting/list.go:185 +0x1d0
github.com/dgraph-io/dgraph/posting.GetOrCreate(0xc4604419d0, 0x10, 0x10, 0xc400000001, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/dgraph-io/dgraph/posting/lists.go:345 +0x1a3
github.com/dgraph-io/dgraph/worker.processTask(0x6363230, 0xc47a0966c0, 0xc4b7961500, 0x1, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/dgraph-io/dgraph/worker/task.go:292 +0xac8
github.com/dgraph-io/dgraph/worker.ProcessTaskOverNetwork(0x6363230, 0xc47a0966c0, 0xc4b7961500, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/dgraph-io/dgraph/worker/task.go:63 +0x8a9
github.com/dgraph-io/dgraph/query.ProcessGraph(0x4c8ed00, 0xc47a0966c0, 0xc4538186c0, 0xc4d4443d40, 0xc47a096960)
	/Users/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1528 +0x260a
created by github.com/dgraph-io/dgraph/query.ProcessGraph
	/Users/travis/gopath/src/github.com/dgraph-io/dgraph/query/query.go:1758 +0x110f
```

**Comment by pawanrawal** [comment]
This happens if you try to do `Get` after closing the KV store. This was happening in Dgraph because some queries might still be going on after the store has been closed.

**Comment by pawanrawal** [comment]
KV shouldn't be called after closing, so we don't need to fix this issue.
