### ISSUE TITLE
Unexpected page fault on iteration

### ISSUE THREAD

**Issue by connorgorman** [dgraph-io/badger#946]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.7 darwin/amd64

Note: issue was also seen on linux
</pre>

### What version of Badger are you using?
1.6.0

### Does this issue reproduce with the latest master?

A different issue manifests
```
panic: Unclosed iterator at time of Txn.Discard.
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13fd407]

goroutine 13 [running]:
github.com/dgraph-io/badger.(*Txn).Discard(0xc01901c080)
	/github.com/dgraph-io/badger/txn.go:446 +0xde
panic(0x14faf20, 0x19c9170)
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:522 +0x1b5
github.com/dgraph-io/badger/skl.(*Skiplist).IncrRef(...)
	/github.com/dgraph-io/badger/skl/skl.go:86
github.com/dgraph-io/badger.(*DB).getMemTables(0xc00015f180, 0x0, 0x0, 0x0, 0x0)
	/github.com/dgraph-io/badger/db.go:497 +0xd7
github.com/dgraph-io/badger.(*Txn).NewIterator(0xc01901c080, 0x1, 0x64, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/github.com/dgraph-io/badger/iterator.go:409 +0x75
github.com/dgraph-io/badger/badger.iterate.func1(0xc01901c080, 0x0, 0x0)
	/github.com/dgraph-io/badger/badger/main_test.go:475 +0xa3
github.com/dgraph-io/badger.(*DB).View(0xc00015f180, 0x15ae858, 0x0, 0x0)
	/github.com/dgraph-io/badger/txn.go:683 +0x91
github.com/dgraph-io/badger/badger.iterate(0xc00015f180)
	/github.com/dgraph-io/badger/badger/main_test.go:473 +0xad
created by github.com/dgraph-io/badger/badger.TestCrash
	/github.com/dgraph-io/badger/badger/main_test.go:528 +0x155
```

### What are the hardware specifications of the machine (RAM, OS, Disk)?
8GB, Ubuntu, SSD 

### What did you do?

Preloaded a DB with a variety of keys
```
package main

import (
	"fmt"
	"github.com/dgraph-io/badger"
	"time"
)

func iterate(db *badger.DB) {
	t := time.NewTicker(10 * time.Millisecond)

	for range t.C {
		err := db.View(func (tx *badger.Txn) error {
			opts := badger.DefaultIteratorOptions
			it := tx.NewIterator(opts)
			defer it.Close()
			for it.Rewind(); it.Valid(); it.Next() {}
			return nil
		})
		if err != nil {
			fmt.Printf("error iterating: %v\n", err)
		}
	}
}

func main() {
	opts := badger.DefaultOptions("")
	db, err := badger.Open(opts)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	go iterate(db)

	time.Sleep(5 * time.Second)
}
```

### What did you expect to see?
DB closing nicely. This is also something that I've seen in a running system with an iterator. It seems like the memory map may be unmapped without considering if it's bytes are currently being used resulting in a page fault

### What did you see instead?
I don't think the below stacktrace is mitigated on master based on a review of the commits, but haven't been able to reproduce
```
badger 2019/07/28 21:38:41 INFO: All 12 tables opened in 3.301s
badger 2019/07/28 21:38:41 INFO: Replaying file id: 36 at offset: 119010948
badger 2019/07/28 21:38:41 INFO: Replay took: 83.744µs
badger 2019/07/28 21:38:41 DEBUG: Value log discard stats empty
badger 2019/07/28 21:38:46 INFO: Got compaction priority: {level:0 score:1.73 dropPrefix:[]}
unexpected fault address 0x5fa9c69
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x5fa9c69 pc=0x1366e6d]

goroutine 48 [running]:
runtime.throw(0x14b40eb, 0x5)
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/panic.go:617 +0x72 fp=0xc000181ba0 sp=0xc000181b70 pc=0x102dba2
runtime.sigpanic()
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/signal_unix.go:397 +0x401 fp=0xc000181bd0 sp=0xc000181ba0 pc=0x1042161
encoding/binary.bigEndian.Uint16(...)
	/usr/local/Cellar/go/1.12.7/libexec/src/encoding/binary/binary.go:101
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger/table.(*header).Decode(0xc000181c0c, 0x5fa9c69, 0x967, 0x1763e16, 0xc000181c08)
	vendor/github.com/dgraph-io/badger/table/builder.go:56 +0x1d fp=0xc000181be0 sp=0xc000181bd0 pc=0x1366e6d
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger/table.(*blockIterator).Next(0xc022905e60)
	vendor/github.com/dgraph-io/badger/table/iterator.go:139 +0xea fp=0xc000181c30 sp=0xc000181be0 pc=0x13689ea
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger/table.(*Iterator).next(0xc00019a600)
	vendor/github.com/dgraph-io/badger/table/iterator.go:348 +0x9f fp=0xc000181ca8 sp=0xc000181c30 pc=0x136978f
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger/table.(*Iterator).Next(0xc00019a600)
	vendor/github.com/dgraph-io/badger/table/iterator.go:399 +0x44 fp=0xc000181cc0 sp=0xc000181ca8 pc=0x1369cb4
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger/table.(*ConcatIterator).Next(0xc00934c370)
	vendor/github.com/dgraph-io/badger/table/iterator.go:509 +0x33 fp=0xc000181ce0 sp=0xc000181cc0 pc=0x136a393
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger/y.(*MergeIterator).Next(0xc00934c410)
	vendor/github.com/dgraph-io/badger/y/iterator.go:216 +0x52 fp=0xc000181d38 sp=0xc000181ce0 pc=0x1361ab2
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger.(*Iterator).parseItem(0xc009346320, 0xc009346301)
	vendor/github.com/dgraph-io/badger/iterator.go:592 +0x484 fp=0xc000181e60 sp=0xc000181d38 pc=0x13a5024
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger.(*Iterator).Next(0xc009346320)
	vendor/github.com/dgraph-io/badger/iterator.go:505 +0x110 fp=0xc000181e80 sp=0xc000181e60 pc=0x13a49b0
main.iterate.func1(0xc04291e100, 0x0, 0x0)
	main.go:17 +0xfe fp=0xc000181f18 sp=0xc000181e80 pc=0x13d599e
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger.(*DB).View(0xc0000a6380, 0x14d4438, 0x0, 0x0)
	vendor/github.com/dgraph-io/badger/txn.go:683 +0x91 fp=0xc000181f48 sp=0xc000181f18 pc=0x13bdf81
main.iterate(0xc0000a6380)
	main.go:13 +0xad fp=0xc000181fd8 sp=0xc000181f48 pc=0x13d565d
runtime.goexit()
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000181fe0 sp=0xc000181fd8 pc=0x10598e1
created by main.main
	main.go:34 +0x134

goroutine 1 [syscall]:
syscall.syscall(0x1150c80, 0x26bd8000, 0x4569674, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.12.7/libexec/src/runtime/sys_darwin.go:63 +0x2e
github.com/stackrox/rox/vendor/golang.org/x/sys/unix.munmap(0x26bd8000, 0x4569674, 0x2b141673, 0xc0000dca58)
	vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:2323 +0x58
github.com/stackrox/rox/vendor/golang.org/x/sys/unix.(*mmapper).Munmap(0x1860940, 0x26bd8000, 0x4569674, 0x4569674, 0x0, 0x0)
	vendor/golang.org/x/sys/unix/syscall_unix.go:149 +0x14e
github.com/stackrox/rox/vendor/golang.org/x/sys/unix.Munmap(...)
	vendor/golang.org/x/sys/unix/syscall_bsd.go:615
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger/y.Munmap(...)
	vendor/github.com/dgraph-io/badger/y/mmap_unix.go:41
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger/table.(*Table).Close(0xc0001643c0, 0x14d4c88, 0xc00011c780)
	vendor/github.com/dgraph-io/badger/table/table.go:196 +0x9e
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger.(*levelHandler).close(0xc00011c780, 0x0, 0x0)
	vendor/github.com/dgraph-io/badger/level_handler.go:186 +0xc3
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger.(*levelsController).cleanupLevels(0xc0001325b0, 0xc00018a101, 0xc042917c48)
	vendor/github.com/dgraph-io/badger/levels.go:212 +0x7c
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger.(*levelsController).close(0xc0001325b0, 0xc00000eec0, 0xc00000eec0)
	vendor/github.com/dgraph-io/badger/levels.go:897 +0x2b
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger.(*DB).close(0xc0000a6380, 0xc042917d60, 0x10)
	vendor/github.com/dgraph-io/badger/db.go:429 +0x1ff
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger.(*DB).Close.func1()
	vendor/github.com/dgraph-io/badger/db.go:350 +0x33
sync.(*Once).Do(0xc0000a6660, 0xc042917da0)
	/usr/local/Cellar/go/1.12.7/libexec/src/sync/once.go:44 +0xb3
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger.(*DB).Close(0xc0000a6380, 0x50, 0x1)
	vendor/github.com/dgraph-io/badger/db.go:349 +0x6e
main.main()
	main.go:37 +0x148

goroutine 19 [select]:
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger/y.(*WaterMark).process(0xc0000a2940, 0xc0000985c0)
	vendor/github.com/dgraph-io/badger/y/watermark.go:225 +0x2d1
created by github.com/stackrox/rox/vendor/github.com/dgraph-io/badger/y.(*WaterMark).Init
	vendor/github.com/dgraph-io/badger/y/watermark.go:74 +0xc9

goroutine 20 [select]:
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger/y.(*WaterMark).process(0xc0000a2980, 0xc0000985c0)
	vendor/github.com/dgraph-io/badger/y/watermark.go:225 +0x2d1
created by github.com/stackrox/rox/vendor/github.com/dgraph-io/badger/y.(*WaterMark).Init
	vendor/github.com/dgraph-io/badger/y/watermark.go:74 +0xc9

goroutine 35 [select]:
github.com/stackrox/rox/vendor/github.com/dgraph-io/badger.(*DB).updateSize(0xc0000a6380, 0xc00018e060)
	vendor/github.com/dgraph-io/badger/db.go:1005 +0x12f
created by github.com/stackrox/rox/vendor/github.com/dgraph-io/badger.Open
	vendor/github.com/dgraph-io/badger/db.go:283 +0xa7f

Process finished with exit code 2
```

**Comment by jarifibrahim** [comment]
>Does this issue reproduce with the latest master?
A different issue manifests
panic: Unclosed iterator at time of Txn.Discard.

@connorgorman If you look at the first line of the error you saw on master, it clearly states that you have an unclosed iterator at transaction discard. All open iterators should be closed when the transaction is discarded.

>It seems like the memory map may be unmapped without considering if it's bytes are currently being used resulting in a page fault

Yes, we do unmap the memory when we close the DB. The user isn't expected to use the DB after closing it.

The script you've shared keeps iterating over the DB even after the DB is closed. That is supposed to crash. You should stop the iteration before you close the DB.

I'm closing this issue since this isn't an issue with badger. Feel free to reopen.
