### ISSUE TITLE
SIGILL on macos 10.13.6 when trying to set a key value pair.

### ISSUE THREAD

**Issue by SaleProperly** [dgraph-io/badger#980]
EDIT: The code works with "release/v1.6", but not with the current master.
EDIT 2: Simplified code a little and regenerated error.

I am using commit 9d7b751e85c981d34e6351520919f5c0547c1379 from Aug 9, 2019. The error also happens with the current commit 74ed6da2c776a6b4941596df9da3ff84a0703c70.

**Doesn't** work on:
macos 10.13.6, 16GB ram, SSD
go version go1.12.7 darwin/amd64 **or** go version go1.9.4 darwin/amd64

**Does** work on:
Amazon EC2 t2.micro
Ubuntu 18.04.2 LTS, 1GB ram
go version go1.9.4 linux/amd64

I have no trouble getting the code to run on an ec2 ubuntu instance, but am getting a SIGILL on macos.

The code I am using is essentially straight from the README:

```
package main

import "github.com/dgraph-io/badger"
import "fmt"

func main() {

	db, err := badger.Open(badger.DefaultOptions("database"))

	if err != nil {
		panic(err)
	}
	defer db.Close()

	err = db.Update(func(txn *badger.Txn) error {
		err := txn.Set([]byte("answer"), []byte("42"))
		return err
	})

	err = db.View(func(txn *badger.Txn) error {

		item, err := txn.Get([]byte("answer"))

		if err != nil {
			panic(err)
		}

		err = item.Value(func(val []byte) error {

			fmt.Printf("The answer is: %s\n", val)
			return nil

		})

		if err != nil {
			panic(err)
		}

		return nil
	})
}
```

The output with the SIGILL is here:

```
badger 2019/08/12 20:55:22 INFO: All 0 tables opened in 0s
SIGILL: illegal instruction
PC=0x105943c m=7 sigcode=1

goroutine 1 [running]:
runtime.aeshashbody()
	/usr/local/go/src/runtime/asm_amd64.s:894 +0x1c fp=0xc009345cb0 sp=0xc009345ca8 pc=0x105943c
github.com/dgraph-io/ristretto/z.AESHash(...)
	/Users/user1/go/src/github.com/dgraph-io/ristretto/z/rtutil.go:50
github.com/dgraph-io/badger.(*Txn).modify(0xc009334100, 0xc0000948a0, 0xc000000008, 0xc00005a080)
	/Users/user1/go/src/github.com/dgraph-io/badger/txn.go:335 +0x134 fp=0xc009345d28 sp=0xc009345cb0 pc=0x13c20e4
github.com/dgraph-io/badger.(*Txn).SetEntry(...)
	/Users/user1/go/src/github.com/dgraph-io/badger/txn.go:356
github.com/dgraph-io/badger.(*Txn).Set(...)
	/Users/user1/go/src/github.com/dgraph-io/badger/txn.go:347
main.main.func1(0xc009334100, 0x14db5e8, 0xc009334100)
	/Users/user1/go/src/badgerTest/main.go:16 +0xd4 fp=0xc009345d68 sp=0xc009345d28 pc=0x13db5f4
github.com/dgraph-io/badger.(*DB).Update(0xc0000e9180, 0x14dc0d0, 0x0, 0x0)
	/Users/user1/go/src/github.com/dgraph-io/badger/txn.go:696 +0x85 fp=0xc009345d98 sp=0xc009345d68 pc=0x13c3d95
main.main()
	/Users/user1/go/src/badgerTest/main.go:15 +0x149 fp=0xc009345f98 sp=0xc009345d98 pc=0x13db4a9
runtime.main()
	/usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc009345fe0 sp=0xc009345f98 pc=0x102f65c
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc009345fe8 sp=0xc009345fe0 pc=0x1059a41

goroutine 5 [select]:
github.com/dgraph-io/badger/y.(*WaterMark).process(0xc00005a540, 0xc00000f0e0)
	/Users/user1/go/src/github.com/dgraph-io/badger/y/watermark.go:225 +0x2d1
created by github.com/dgraph-io/badger/y.(*WaterMark).Init
	/Users/user1/go/src/github.com/dgraph-io/badger/y/watermark.go:74 +0xc9

goroutine 6 [select]:
github.com/dgraph-io/badger/y.(*WaterMark).process(0xc00005a580, 0xc00000f0e0)
	/Users/user1/go/src/github.com/dgraph-io/badger/y/watermark.go:225 +0x2d1
created by github.com/dgraph-io/badger/y.(*WaterMark).Init
	/Users/user1/go/src/github.com/dgraph-io/badger/y/watermark.go:74 +0xc9

goroutine 7 [select]:
github.com/dgraph-io/badger.(*DB).updateSize(0xc0000e9180, 0xc00000f1a0)
	/Users/user1/go/src/github.com/dgraph-io/badger/db.go:1021 +0x12f
created by github.com/dgraph-io/badger.Open
	/Users/user1/go/src/github.com/dgraph-io/badger/db.go:289 +0xb1c

goroutine 10 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc0001085b0, 0xc00000e0e0)
	/Users/user1/go/src/github.com/dgraph-io/badger/levels.go:351 +0x1fc
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/Users/user1/go/src/github.com/dgraph-io/badger/levels.go:332 +0x89

goroutine 11 [select]:
github.com/dgraph-io/badger.(*levelsController).runWorker(0xc0001085b0, 0xc00000e0e0)
	/Users/user1/go/src/github.com/dgraph-io/badger/levels.go:340 +0x122
created by github.com/dgraph-io/badger.(*levelsController).startCompact
	/Users/user1/go/src/github.com/dgraph-io/badger/levels.go:332 +0x89

goroutine 12 [chan receive]:
github.com/dgraph-io/badger.(*DB).flushMemtable(0xc0000e9180, 0xc00000e260, 0x0, 0x0)
	/Users/user1/go/src/github.com/dgraph-io/badger/db.go:935 +0xb3
github.com/dgraph-io/badger.Open.func4(0xc0000100b0)
	/Users/user1/go/src/github.com/dgraph-io/badger/db.go:303 +0x37
created by github.com/dgraph-io/badger.Open
	/Users/user1/go/src/github.com/dgraph-io/badger/db.go:302 +0x1548

goroutine 20 [select]:
github.com/dgraph-io/badger.(*DB).doWrites(0xc0000e9180, 0xc000082160)
	/Users/user1/go/src/github.com/dgraph-io/badger/db.go:719 +0x3f8
created by github.com/dgraph-io/badger.Open
	/Users/user1/go/src/github.com/dgraph-io/badger/db.go:337 +0x108d

goroutine 21 [chan receive]:
github.com/dgraph-io/badger.(*valueLog).waitOnGC(0xc0000e9300, 0xc000082180)
	/Users/user1/go/src/github.com/dgraph-io/badger/value.go:1343 +0x67
created by github.com/dgraph-io/badger.Open
	/Users/user1/go/src/github.com/dgraph-io/badger/db.go:340 +0x1155

goroutine 22 [select]:
github.com/dgraph-io/badger.(*publisher).listenForUpdates(0xc00009d500, 0xc0000821a0)
	/Users/user1/go/src/github.com/dgraph-io/badger/publisher.go:67 +0x158
created by github.com/dgraph-io/badger.Open
	/Users/user1/go/src/github.com/dgraph-io/badger/db.go:343 +0x121d

rax    0xc000018228
rbx    0xc000018228
rcx    0x6
rdx    0xc009345cc8
rdi    0x2
rsi    0x2
rbp    0xc009345d18
rsp    0xc009345ca8
r8     0xc00001822e
r9     0x3fffffff
r10    0x149aa20
r11    0x0
r12    0xc
r13    0xd9
r14    0x1548dda
r15    0x0
rip    0x105943c
rflags 0x10246
cs     0x2b
fs     0x0
gs     0x0
exit status 2
```

Regardless of how I write this, it seems like the offending code is related to this call:

`err := txn.Set([]byte("answer"), []byte("42"))`

I had similar results using other code from around the web.

**Comment by SaleProperly** [comment]
I've narrowed it down to the breaking commit.

7372ede1e54baea176e38ffdda4839e5a8bef55c is the first commit where this error appears.

**Comment by ashish-goswami** [comment]
Hey @SaleProperly, above program is working fine for mac 10.13.4. Let us try on 10.13.6 as well.

**Comment by ashish-goswami** [comment]
Hey @SaleProperly, I tried to run above code in mac 10.13.6 with go1.12.7, its working fine. I am not seeing any SIGILL.

**Comment by SaleProperly** [comment]
@ashish-goswami could it be related to the model of hardware I am using? (2010 mid year MacBook pro) 

This error definitely persists for me on any commit after switching to aeshash.

Is there any trouble shooting you can suggest I do on my end to help us narrow down the cause?

**Comment by ashish-goswami** [comment]
@SaleProperly This looks like hardware issue. My mode is early 2015 macbook pro.
We run tests on travis also. It passes there too.

**Comment by ashish-goswami** [comment]
Hey @SaleProperly, closing this for now. Feel free to open it if required.

**Comment by liaonaibo** [comment]
The error also happens to me with the current master. I was trying to use the "release/v1.6" and got the same error. I can not fix it.

**Comment by ashish-goswami** [comment]
Hey @liaonaibo, what Mac model are you using?

**Comment by manishrjain** [comment]
Let's figure out what does Go team do for AESHash on older platforms. We could also introduce build flags to use either AESHash or something more platform agnostic.

**Comment by SaleProperly** [comment]
Hey @manishrjain, do you think we could craft the shortest bit of code that would cause this error on affected hardware?

If I had that, I would open an issue on aeshash itself.

**Comment by ashish-goswami** [comment]
Hey @SaleProperly @liaonaibo can you check if **_aes_** instruction set is available on your system?
For mac you can try: **_sysctl -a | grep cpu.feat_**
For linux you can try: **_lscpu_**

**Comment by ashish-goswami** [comment]
Hey @SaleProperly @liaonaibo We have just merged fix for the issue. Please check if you are still facing this issue.

**Comment by SaleProperly** [comment]
@ashish-goswami I just updated both badger and ristretto. Everything is working. No more error.

Thanks.

I am using commit fbcd608981982d2d8c1612d310ac491d01dbde96 for badger and eb48d2f7 for ristretto.
